### PR TITLE
Feature wall distance

### PR DESCRIPTION
**Pull request by economon**
This contains a new implementation of tree-based searches with a first application to computing wall distances for RANS calculations (thanks due to Edwin!). Initial scaling tests look good, but still completing some... checking for correctness now.

### CODE REVIEW

**Comment by economon** [comment]
Everything looks good here with the ADT search. Merging this into the develop branch. Two notes:

1. I switched MPI_Allgatherv() to SU2_MPI:Allgather() temporarily until we can properly treat the wrapper. This will be easy to change. The code is slightly less pretty, but same results.

2. Scaling results look very good out to 96 cores and can be ~100x faster than the brute force search. I'll run on O(1000) cores as soon as I have access again to make sure there aren't any hidden problems at scale.

**Comment by hlkline** [comment]
Looks good, thanks @vdweide, @economon.
I took a  quick peak, it looks like there wasn't any change to the interpolation routines - can this same tree search be applied to finding nearest neighbors in the interpolation routines, and if so did you look into that yet or would that be a project for the future?

**Comment by vdweide** [comment]
I expect that the tree search can be used for the interpolation routines without a problem. However, we have not looked into that yet.

**Comment by LaSerpe** [comment]
Heather, all,


As you know I'm working on sliding meshes and that's something we were really looking forward.

In my opinion including the ADT search inside the interpolator class to find the nearest neighbour will be mandatory when we will get to simulate multi-stage turbines.

I did't have a proper look at those routines yet but I also do not expect any particular problem in using them inside the interpolator class.


(Actually one item in my "todo" list is indeed to include those routines in the interpolator class.)



Giulio

________________________________
Da: Edwin van der Weide <notifications@github.com>
Inviato: giovedì 7 luglio 2016 23.47.21
A: su2code/SU2
Oggetto: Re: [su2code/SU2] Feature wall distance (#288)


I expect that the tree search can be used for the interpolation routines without a problem. However, we have not looked into that yet.

-

**Pull request merged**
