### PR TITLE
Remove legacy Poisson & Wave solvers

### PR DESCRIPTION
**Pull request by rsanfer**
## Proposed Changes
This pull request removes the old Poisson and Wave solvers, which are currently unsupported, and replaces the legacy heat solver with the FVM heat solver incorporated in #505.

## Related Work
This is an intermediate step before there is a general restructuring of the input and output, currently under development.

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [X] I am submitting my contribution to the develop branch.
- [X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [X] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by economon** [comment]
I can add a proper review soon, but first, will this cause any conflicts for you, @koodlyakshay, in terms of functions/file deletions related to the pressure poisson solve in the solver you are working on in a separate branch?

**Comment by rsanfer** [comment]
Thanks, @jayantmukho ,
those changes should be reverted already. In my computer, bootstrap was not working for some reason, so I needed to have @talbring to run it in his and revert some of the changes. 
That said, I think we should look into moving to a newer version of automake. We are still maintaining 1.12.5 (released in 2012)...

**Comment by rsanfer** [comment]
Any further comment on this before we merge it in? @economon, you mentioned you wanted to add something, right?

**Comment by koodlyakshay** [comment]
Hi Tom,

I spoke to Ruben and Tim at the meeting, this won't be a problem to my work. 

Akshay

**Comment by WenyinWei** [comment]
Hello guys, there are some remaining dead declarations in `solver_structure.hpp`, at about 10860 line. Anyone willing to delete them when restructuring the `solver_structure` file?

```
/*! \class CPoissonSolver
 *  \brief Main class for defining the poisson potential solver.
 *  \author F. Palacios
 *  \date May 3, 2010.
 */
class CPoissonSolver : public CSolver {
private:
  su2double *Source_Vector;      /*!< \brief Auxiliary vector for storing element source vector. */
  su2double **StiffMatrix_Elem; /*!< \brief Auxiliary matrices for storing point to point Stiffness Matrices. */
  su2double **StiffMatrix_Node;  /*!< \brief Auxiliary matrices for storing point to point Stiffness Matrices. */
 ```

**Pull request merged**
