### PR TITLE
Let's add the contributor covenant

### PR DESCRIPTION
**Pull request by economon**
As discussed at the 3rd SU2 Developers Meeting, we would like to make sure that the SU2 project remains as it has been since the start: an open and welcoming place for any and all contributors. 

Let's add the contributor covenant as a proactive way to set our expectations as a community (which is growing each day!). I have listed my own email address as a contact point initially.

### CODE REVIEW

**Comment by talbring** [comment]
Thanks Tom! To me that looks like an important step. We can merge that in asap!

**Comment by hlkline** [comment]
Just added a couple of quick edits (some of it was punctuation). 
Regarding adding a 'consequences' list: I've seen this done in other policies, and I think that it is a good idea to explicitly list consequences not only because it makes it a bit more 'real' for those who might need some convincing, but also because uncertainty about the consequences can lead to unnecessary fear and defensiveness on both sides (of a situation that hopefully will never come about).
Please feel free to revert those changes and/or change the consequences to fit what you think is appropriate.

**Comment by vdweide** [comment]
Let's merge it in then.

**Comment by vdweide** [comment]
@economon, I am not sure if you still need this branch, so I didn't delete it.

**Pull request merged**
