### PR TITLE
Added documentation checkbox

### PR DESCRIPTION
**Pull request by WallyMaier**
Although a minor change, I think this will help SU2 stay up-to-date documentation wise with future updates. Staying ahead of documentation in future PRs will prevent further lag, in my opinion.

### Related work
I think this begins to address the documentation woes mentioned the issue #775 

- [x ] I am submitting my contribution to the develop branch.
- [N/A] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [N/A ] My contribution is commented and consistent with SU2 style.
- [ N/A] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by oleburghardt** [comment]
Hi @WallyMaier, good thought that you'd like the developers to not lose sight of proper documentation, especially for all the new stuff.
Though _appropriate_ can be very subjective and seems too vague to me. It could be code comments, a tutorial, contributions to the Docs page, a scientific article, ...
So in the end it might be too easy ticking this box... (making it an almost redundant addition in the worst case). Can be think of a more specific formulation?

**Comment by WallyMaier** [comment]
Absolutely.  Originally, I had thought to say update Docs page/Tutorial/Config_template".  In my opinion, those things arent covered with the current format.  However, I am open to ideas!

**Comment by clarkpede** [comment]
As far as documenting the code itself, you could add the requirement that Doxygen generate no new warnings or errors.

**Comment by WallyMaier** [comment]
True. I was thinking more from the user point-of-view, to be sure people little little experience can use SU2 easier.  Similar to something Tim has already started in the Docs page.  The idea here is just to be sure new features are easily usable/accessible for people unfamiliar.

**Pull request merged**
