### PR TITLE
Fix driver/config restructure bug

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
@rsanfer , @talbring please keep the testcases up to date with the new options you are introducing, avoidable bugs are starting to pass...

## PR Checklist
- [X] I am submitting my contribution to the develop branch.
- [X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [X] My contribution is commented and consistent with SU2 style.
- [X] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by talbring** [comment]
@pcarruscag I would not call that an avoidable bug considering the fact that the regression test passed.

**Comment by pcarruscag** [comment]
It passed because the config options were not updated and so no mesh deformation was specified for any of the FSI cases.

**Comment by talbring** [comment]
If this has no influence on the test values then we should change these cases I would say.

**Comment by economon** [comment]
Let’s try to keep it positive here.. @talbring has an interesting point that the tests should show some sensitivity to major changes like the grid deformation not being specified. Can they be made more sensitive to this?

**Comment by pcarruscag** [comment]
I agree, but some do [pick up](https://github.com/su2code/SU2/commits/develop/TestCases/disc_adj_fsi/Airfoil_2d/config.cfg) those changes, just not all of them.

Anyway, you'll notice I put an assert for the condition that was causing the problem instead of an "mpi error". That is inline with the philosophy that errors/exceptions are to deal with user errors and asserts to help debugging (they are ignored with -DNDEBUG). I can off-course change it.

**Pull request merged**
