### PR TITLE
CMake support for SU2

### PR DESCRIPTION
**Pull request by dkavolis**
## Proposed Changes
Added CMake build support for SU2. With this, many popular IDEs will be able to use SU2 as a project with minimal setup. CMake also enables to add dependencies more easily since most libraries have CMake support. `vcpkg` is great for the libraries available there.

SU2 CMake has the same build options as autotools but uses CMake to find system libraries and compilers (MKL, Mutationpp, MPI and Python currently). No longer need to specify paths to compilers/libraries if they are in standard locations. In addition, compile flags can be modified from CMake. There is no need to use `preconfigure.py` anymore since downloading/unpacking is handled by CMake and is system-agnostic.

At the moment, all library targets are static but that could be easily changed to be configurable from CMake. The installation directory is `${CMAKE_PREFIX_PATH}/bin`.

Similarly to autotools, some build options are disabled if built with Codi forward/reverse datatypes or without MPI. Note that SWIG fails to compile `pySU2ad` with `Nothing known about namespace 'medi'` in `Common/include/mpi_structure.hpp:57` without `-includeall` SWIG option but then it takes forever to generate the wrapper (more than 15 minutes on my machine, stopped early). I suggest removing `using namespace` declarations and either importing used symbols explicitly with `using` or prepending namespace name, `clang-tidy` warns against them and it makes the code clearer.

SU2 CMake options are:
* Build modules:
  * `SU2_BUILD_CFD`: `ON|OFF`
  * `SU2_BUILD_DEF`: `ON|OFF`, disabled when building with Codi
  * `SU2_BUILD_DOT`: `ON|OFF`, disabled when building with Codi forward
  * `SU2_BUILD_GEO`: `ON|OFF`, disabled when building with Codi
  * `SU2_BUILD_MSH`: `ON|OFF`, disabled when building with Codi
  * `SU2_BUILD_PY_WRAPPER`: `ON|OFF`, disabled when building with Codi forward
  * `SU2_BUILD_SOL`: `ON|OFF`, disabled when building with Codi
* Enable modules:
  * `SU2_ENABLE_CGNS`: 
    * `SU2_CGNS_CPPFLAGS`: flags to pass when compiling CGNS
  * `SU2_ENABLE_CODI`: `no|forward|reverse`
    * `SU2_CODI_CPPFLAGS`: flags to pass to SU2 modules when compiling with Codi
  * `SU2_ENABLE_METIS`: `ON|OFF`
    * `SU2_METIS_CPPFLAGS`: flags to pass when compiling Metis
  * `SU2_ENABLE_MKL`: `ON|OFF`
  * `SU2_ENABLE_MPI`: `ON|OFF`
  * `SU2_ENABLE_MUTATIONPP`: `ON|OFF`
  * `SU2_ENABLE_PARMETIS`: `ON|OFF`, only available when `SU2_ENABLE_MPI` is `ON`
    * `SU2_PARMETIS_CPPFLAGS`: flags to pass when compiling Parmetis
  * `SU2_ENABLE_TECIO`: `ON|OFF`
    * `SU2_TECIO_CPPFLAGS`: flags to pass when compiling Tecio and TecioMPI
    * `SU2_TECIOMPI_CPPFLAGS`: flags to pass when compiling TecioMPI, requires `SU2_ENABLE_MPI`

There is an additional variable that is recognized by CMake scripts - `DEBUG`, turning it `ON` enables additional `STATUS` messages, mainly to check that correct include directories, compile definitions and linked libraries were set up correctly.

The remaining options like install location and compilers are handled by CMake. Tested this on Ubuntu with CMake 3.15.5 and everything except `pySU2ad` wrapper compiles. Haven't tested on earlier CMake versions so there might be bugs with them but they should be easy to resolve if any.

I have based the CMake scripts on autotools scripts so there's no Pastix/Blas options yet. [FindBLAS](https://cmake.org/cmake/help/latest/module/FindBLAS.html), [FindPastix](https://github.com/eigenteam/eigen-git-mirror/blob/master/cmake/FindPastix.cmake), [FindScotch](https://github.com/eigenteam/eigen-git-mirror/blob/master/cmake/FindScotch.cmake)

## Related Work
*Resolve any issues (bug fix or feature request), note any related PRs, or mention interactions with the work of others, if any.*

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [x] My contribution is commented and consistent with SU2 style.
- [x] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by juanjosealonso** [comment]
Wonderful contribution. Thanks for doing all that. Streamlining the dev process is very helpful and cmake is definitely becoming a standard.

Best,

Juan

On Nov 10, 2019, at 11:24 AM, Daumantas Kavolis <notifications@github.com> wrote:

﻿
Proposed Changes

Added CMake build support for SU2. With this, many popular IDEs will be able to use SU2 as a project with minimal setup. CMake also enables to add dependencies more easily since most libraries have CMake support. vcpkg is great for the libraries available there.

SU2 CMake has the same build options as autotools but uses CMake to find system libraries and compilers (MKL, Mutationpp, MPI and Python currently). No longer need to specify paths to compilers/libraries if they are in standard locations. In addition, compile flags can be modified from CMake. There is no need to use preconfigure.py anymore since downloading/unpacking is handled by CMake and is system-agnostic.

At the moment, all library targets are static but that could be easily changed to be configurable from CMake. The installation directory is ${CMAKE_PREFIX_PATH}/bin.

Similarly to autotools, some build options are disabled if built with Codi forward/reverse datatypes or without MPI. Note that SWIG fails to compile pySU2ad with Nothing known about namespace 'medi' in Common/include/mpi_structure.hpp:57 without -includeall SWIG option but then it takes forever to generate the wrapper (more than 15 minutes on my machine, stopped early). I suggest removing using namespace declarations and either importing used symbols explicitly with using or prepending namespace name, clang-tidy warns against them by default and it makes the code clearer.

SU2 CMake options are:

  *   Build modules:
     *   SU2_BUILD_CFD: ON|OFF
     *   SU2_BUILD_DEF: ON|OFF, disabled when building with Codi
     *   SU2_BUILD_DOT: ON|OFF, disabled when building with Codi forward
     *   SU2_BUILD_GEO: ON|OFF, disabled when building with Codi
     *   SU2_BUILD_MSH: ON|OFF, disabled when building with Codi
     *   SU2_BUILD_PY_WRAPPER: ON|OFF, disabled when building with Codi forward
     *   SU2_BUILD_SOL: ON|OFF, disabled when building with Codi
  *   Enable modules:
     *   SU2_ENABLE_CGNS:
        *   SU2_CGNS_CPPFLAGS: flags to pass when compiling CGNS
     *   SU2_ENABLE_CODI: no|forward|reverse
        *   SU2_CODI_CPPFLAGS: flags to pass to SU2 modules when compiling with Codi
     *   SU2_ENABLE_METIS: ON|OFF
        *   SU2_METIS_CPPFLAGS: flags to pass when compiling Metis
     *   SU2_ENABLE_MKL: ON|OFF
     *   SU2_ENABLE_MPI: ON|OFF
     *   SU2_ENABLE_MUTATIONPP: ON|OFF
     *   SU2_ENABLE_PARMETIS: ON|OFF, only available when SU2_ENABLE_MPI is ON
        *   SU2_PARMETIS_CPPFLAGS: flags to pass when compiling Parmetis
     *   SU2_ENABLE_TECIO: ON|OFF
        *   SU2_TECIO_CPPFLAGS: flags to pass when compiling Tecio and TecioMPI
        *   SU2_TECIOMPI_CPPFLAGS: flags to pass when compiling TecioMPI, requires SU2_ENABLE_MPI

There is an additional variable that is recognized by CMake scripts - DEBUG, turning it ON enables additional STATUS messages, mainly to check that correct include directories, compile definitions and linked libraries were set up correctly.

The remaining options like install location and compilers are handled by CMake. Tested this on Ubuntu with CMake 3.15.5 and everything except pySU2ad wrapper compiles. Haven't tested on earlier CMake versions so there might be bugs with them but they should be easy to resolve if any.

Related Work

Resolve any issues (bug fix or feature request), note any related PRs, or mention interactions with the work of others, if any.

PR Checklist

Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.

  *    I am submitting my contribution to the develop branch.
  *    My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
  *    My contribution is commented and consistent with SU2 style.
  *    I have added a test case that demonstrates my contribution, if necessary.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/su2code/SU2/pull/814

Commit Summary

  *   CMake support for SU2

File Changes

  *   A CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-0> (147)
  *   A Common/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-1> (149)
  *   A SU2_CFD/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-2> (143)
  *   A SU2_DEF/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-3> (13)
  *   A SU2_DOT/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-4> (25)
  *   A SU2_GEO/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-5> (9)
  *   A SU2_MSH/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-6> (8)
  *   A SU2_PY/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-7> (24)
  *   A SU2_PY/pySU2/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-8> (62)
  *   A SU2_SOL/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-9> (12)
  *   A cmake-format.yaml<https://github.com/su2code/SU2/pull/814/files#diff-10> (40)
  *   A cmake/CheckLinkerFlag.cmake<https://github.com/su2code/SU2/pull/814/files#diff-11> (70)
  *   A cmake/ConfigureCGNS.cmake<https://github.com/su2code/SU2/pull/814/files#diff-12> (11)
  *   A cmake/ConfigureCLI11.cmake<https://github.com/su2code/SU2/pull/814/files#diff-13> (2)
  *   A cmake/ConfigureCodi.cmake<https://github.com/su2code/SU2/pull/814/files#diff-14> (87)
  *   A cmake/ConfigureExternals.cmake<https://github.com/su2code/SU2/pull/814/files#diff-15> (26)
  *   A cmake/ConfigureMKL.cmake<https://github.com/su2code/SU2/pull/814/files#diff-16> (16)
  *   A cmake/ConfigureMPI.cmake<https://github.com/su2code/SU2/pull/814/files#diff-17> (12)
  *   A cmake/ConfigureMetis.cmake<https://github.com/su2code/SU2/pull/814/files#diff-18> (12)
  *   A cmake/ConfigureMutationpp.cmake<https://github.com/su2code/SU2/pull/814/files#diff-19> (12)
  *   A cmake/ConfigureParmetis.cmake<https://github.com/su2code/SU2/pull/814/files#diff-20> (15)
  *   A cmake/ConfigureTecio.cmake<https://github.com/su2code/SU2/pull/814/files#diff-21> (18)
  *   A cmake/ConfigureThreads.cmake<https://github.com/su2code/SU2/pull/814/files#diff-22> (12)
  *   A cmake/FindMKL.cmake<https://github.com/su2code/SU2/pull/814/files#diff-23> (318)
  *   A cmake/FindMPI4PY.cmake<https://github.com/su2code/SU2/pull/814/files#diff-24> (50)
  *   A cmake/LibraryUtils.cmake<https://github.com/su2code/SU2/pull/814/files#diff-25> (239)
  *   A cmake/TLS.cmake<https://github.com/su2code/SU2/pull/814/files#diff-26> (28)
  *   A cmake/check_thread_storage.c<https://github.com/su2code/SU2/pull/814/files#diff-27> (5)
  *   A cmake/functions.cmake<https://github.com/su2code/SU2/pull/814/files#diff-28> (416)
  *   A externals/cgns/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-29> (26)
  *   A externals/metis/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-30> (108)
  *   A externals/parmetis/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-31> (70)
  *   A externals/tecio/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-32> (36)
  *   M externals/tecio/teciompisrc/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-33> (119)
  *   M externals/tecio/teciosrc/CMakeLists.txt<https://github.com/su2code/SU2/pull/814/files#diff-34> (264)

Patch Links:

  *   https://github.com/su2code/SU2/pull/814.patch
  *   https://github.com/su2code/SU2/pull/814.diff

**Comment by dkavolis** [comment]
In terms of streamlining dev process, `clang-format` would help keep code style consistent and `clang-tidy` - consistent code standard and prevent some common programmer errors. Both need a configuration file each in the root directory and most IDEs have built-in support for them.

You might also want to consider `fmt` [library](https://github.com/fmtlib/fmt) for string formatting and output instead of `iostream`s. Using it should improve compile and text output times and make writing/understanding formatted strings much easier compared to the current "chevron hell". A subset of `fmt` is also becoming standard in C++20.

**Comment by talbring** [comment]
Dear Daumantas,

I appreciate your effort in adding support for cmake in SU2. We have recently introduced the Meson build system (https://mesonbuild.com/) (#685, #745) as a candidate to replace automake. A guide on how to use can be found [here](https://su2code.github.io/docs_v7/Build-SU2-From-Source/). The idea is that we will have this system along automake at least for the upcoming version 7 and that we get rid of automake afterwards. Considering that, I don't think that it makes sense to maintain 3 different build systems **at the moment**. I really hate turning contributions down, but this one is three months too late. However, we might reconsider adding support for another build system once we got rid of automake, or, if we feel that meson does not fit our needs.

I am all ears to hear other opinions. However, let's not start a discussion on the advantages/disadvantages of the build systems. Some benefits can be found in the Issue/PR linked above.

**Comment by pcarruscag** [comment]
I agree with @talbring.

**Comment by dkavolis** [comment]
If this is not going to be merged then consider adding `FindMKL.cmake`, `CheckLinkerFlag.cmake` and `LibraryUtils.cmake` and updating `cmake_module_path` in `meson.build` so that meson can find MKL if it was installed from PPA since includes/libraries are not placed in a common directory. https://mesonbuild.com/Dependencies.html#cmake

**Comment by dkavolis** [comment]
> 
> 
> Dear Daumantas,
> 
> I appreciate your effort in adding support for cmake in SU2. We have recently introduced the Meson build system (https://mesonbuild.com/) (#685, #745) as a candidate to replace automake. A guide on how to use can be found [here](https://su2code.github.io/docs_v7/Build-SU2-From-Source/). The idea is that we will have this system along automake at least for the upcoming version 7 and that we get rid of automake afterwards. Considering that, I don't think that it makes sense to maintain 3 different build systems **at the moment**. I really hate turning contributions down, but this one is three months too late. However, we might reconsider adding support for another build system once we got rid of automake, or, if we feel that meson does not fit our needs.
> 
> I am all ears to hear other opinions. However, let's not start a discussion on the advantages/disadvantages of the build systems. Some benefits can be found in the Issue/PR linked above.

Ok, I tried meson with MinGW but couldn't figure out how to link with MSMPI since it's not a part of MinGW.

However, using CMake and with a few source code fixes, I managed to compile nearly every configuration with MSVC. Surprisingly, there were very few errors in SU2. The externals only had a few preprocessor issues. At the moment only MeDiPack fails to compile with MSVC but not with MinGW even though the MPI headers are the same so I suspect it's an issue with MSVC itself, I'm using the latest preview version.

**Comment by talbring** [comment]
You might be interested to hear that I fixed some of the errors that occur using VS2019 in #813. Compilation with meson works fine with the visual studio backend and ninja. 

Still, MediPack does not support MSMPI officially yet (which is strange because its just MPICH in the end), but I will look into it soon. Maybe it works with IntelMPI, though.

**Comment by dkavolis** [comment]
I can guarantee Medi works with MSMPI, my MinGW setup links with `C:/Windows/System32/msmpi.dll` and uses nearly identical MPI header. It most likely is MSVC issue, it often works differently to gcc/clang and has its own set of bugs.

Still, the issue with meson is MinGW pkgconfig cannot find MSMPI because it's not in MinGW directly and there's no way of specifying the library location. So it looks like MinGW build with MPI is currently broken.

**Comment by gladk** [comment]
Thanks for creating this branch. Cmake is really an almost standard in the C++ world now. I could compile the SU2 within the minutes, using this branch.

Just a side note. if there are any plans to push SU2 into the Debian-Ubuntu official repositories, it should probably be much easier to do it with cmake. Files for ninja build-sytem can also be easily generated with -GNinja command line option.

**Pull request closed without merging**
