### PR TITLE
Fix skin friction coefficient

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
I broke it when I defined the reference factor for aerodynamic coefficients in a central location.
Oh well... It would be good to add some regressions for output files, or to try to include more postprocessing quantities in the regressions by adding them to the screen outputs.

### CODE REVIEW

**Comment by pcarruscag** [comment]
Looks like this bug was not released :) (Fortune favours the bold)

**Review by TobiKattmann — APPROVED** [review]
LGTM... and while we're at it, you mentioned yesterday an interview with a NASA guy concerning lgtm ()if I recall correctly). I would be interested in that source :)

And I guess you're onto sth concerning screen output  for reg tests... this `# last four columns` was understood as the rule I guess and sometimes that includes the iterations number :)

**Comment by pcarruscag** [comment]
It was a code review by Jason Turner (https://www.youtube.com/watch?v=RbhufLudVsI&t=1743s&ab_channel=C%E1%90%A9%E1%90%A9WeeklyWithJasonTurner)

Quite a long video, I did not watch it all.

**Comment by pcarruscag** [comment]
Yeah what I'm sayin is put more columns.

**Comment by TobiKattmann** [comment]
Yeah, but listening to Mr Turner is surely well invested time if one is able to follow at  least some of his thoughts. But imo he does a good job in that, I sometimes tune in for cppcast and that is okayish to follow most of the time (but that is not really in depth tbh)

**Pull request merged**
