### PR TITLE
[WIP] Develop for transition model.

### PR DESCRIPTION
**Pull request by sun5k**
Hi, all.

This PR is for implementing various transition models, which are composed of 1~2 additional transport equations.

List of wishes to implement transition model  : 

- [Langtry and Menter model](https://doi.org/10.2514/1.42362) 
- [k-w-gamma](https://doi.org/10.1016/j.paerosci.2012.08.004)
- [SA-AFT](https://doi.org/10.2514/6.2019-0039)

Now working on : 
- Langtry and Menter model

## Related Work

LM feature -> development

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [ ] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [x] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by TobiKattmann** [comment]
Hi Sun5k,
Thanks for tackling the Transition models. As far as I see, you are adopting the CScalarSolver-Base style just as is done for the Turbulence or SpeciesTransport solver (cf #1330  #1388 ) :+1: I think you can stay close to how things are handled in these solvers. The Turbulence solver has another class in the middle though: `CScalarSolver -> CTurbSolver -> CTurbSST/SASolver` I am not sure whether sth like this makes sense for transition models? (because I have no clue of Transition models). Otherwise the CSpeciesSolver is directly based on the CScalarSolver.

Please limit this PR to 1 model only! So in this case just the LM model maybe. It is much easier for you to wrap this PR up with a limited scope instead of trying to do everything at once :) (and it is easier to review for everyone else) In case you then still want to tackle another one once LM is done :D then just open another PR :+1:
 
As unfinished Transition models (or models with a questionable state) are a bit of a companion of SU2 I would also ask you to provide a meaningful testcase with this PR that proves the usability of this feature. I personally like to think of a suitable case at the beginning of development, to adopt a bit a Test-Driven-Development approach but that is of course fully up to you.

In case you did not know about the Developers meeting each Wednesday 4pm Berlin time, now you do. You are kindly invited to ask any questions, just show-and-tell to get some feedback etc. it is a very open round :)

Happy coding, Tobi

**Comment by RichRoos** [comment]
Hey Sun5k! 

I am a master student on the University of Twente, based in the Netherlands. I am also starting to work on the implementation of the Langtry and Menter model into the current version of SU2 for my master thesis (although I have not set-up my own branch yet). The goal would be to validate and hopefully work on some application to test and verify the results compared to other work done in  literature and the latest AIAA transition modeling workshop (https://transitionmodeling.larc.nasa.gov/workshop_i/). 

I would love to know what your plans are with this model and on what timeframe you are working. As we are both working on this topic, it might be beneficial to combine our efforts? If you would like to discuss this, you can send me an email at r.roos@student.utwente.nl.

Kind regards,
Richard

**Comment by marcocera97** [comment]
Hi, i'm working on transition models for my master thesis work and i would join this group. Please contact me at cerabona.marco@gmail.com

**Comment by bigfooted** [comment]
Hi! If you want to work together over github, you can also create a project here:
 https://github.com/su2code/SU2/projects?type=beta and define tasks and divide the work. It would be good if you can sort out what the overlap is and what the unique parts of your research will be.

**Comment by marcocera97** [comment]
I'm at the beginning, so i have no really clear my path. Anyway a soon as
possible i will follow your instructions. Sorry for this difficulty, but to
me a su2 development group is something totally new and i have to clarify
some aspects with my PhD student and with my professor. Thanks for your help
Marco

Il giorno gio 20 gen 2022 alle ore 11:47 Nijso ***@***.***>
ha scritto:

**Comment by sun5k** [comment]
Hello Mr. @RichRoos.


Firstly, I'm really sorry for the late reply. I prefer the Github community board more than private communication. 

Now, Make the structure of Langtry and Menter model was already done. but, I'm under the debugging on the something my mistakes. it is still not solved, then I'm suffering more than 2 weeks.

Are you developing the LM model separately?


Thank you for your attention and suggestion.

**Comment by RichRoos** [comment]
Hey @sun5k, I fell in the same trap I am afraid, as I should have replied sooner...

As for the work: I started to work on a private version so that I could experiment with the code and Github, because I was not experienced with both. In there I, too, based the implementation of the LM version on the old version of the LM transition of SU2 6.3.0. My original plan was to work on my private version until I understood enough to open a Pull request and continue from there, but you were just a little faster :). So that is why I just continued with my own version. I am now at the point of running tests to compare with the original flatplate simulations. I am getting some promising results, but am still checking whether they are correct.

What is your status? Are you still working on this pr? And, if I may ask, what is your main goal with the code? Do you want to use the transition model or are you more focused on the implementation and merging with the main SU2 branch? And lastly, would it be beneficial for us to combine our time, code and results to work on this pr together? :)

Thanks in advance!
Richard

**Pull request closed without merging**
