### PR TITLE
Fix bug for incompressible FSI cases.

### PR DESCRIPTION
**Pull request by rsanfer**
## Proposed Changes
Fixes a bug introduced in #756 for incompressible FSI cases.

## Related Work
This kind of bugs could be avoided with a strategy as suggested by @pcarruscag  in #770

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [x] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by rsanfer** [comment]
I don't know where this extra commit from github actions comes from. @talbring ??

**Comment by talbring** [comment]
Sorry, apparently there is a "bug" in the github actions system ... should work now.

**Comment by talbring** [comment]
I did a force push, so you have to delete your local branch and fetch the new one in case you want to modify it locally.

**Comment by rsanfer** [comment]
Tests are passing, so this wasn't covered. I will make sure it's covered via the tutorials.

**Pull request merged**
