### PR TITLE
Update variable_direct_mean.cpp

### PR DESCRIPTION
**Pull request by paulhzhang**
Fix a bug related to a pointer

### CODE REVIEW

**Comment by economon** [comment]
Hi Paul: thanks for the quick fix (looks good), but can you please submit this pull request to the develop branch rather than the master branch? Thanks!

**Comment by paulhzhang** [comment]
Done. But I hope I clicked the right button.

**Comment by hlkline** [comment]
It looks like you did hit the right button; the tests are running now in https://github.com/su2code/SU2/pull/310

**Comment by talbring** [comment]
Merged the other PR to develop. So I close this one.

**Pull request closed without merging**
