### PR TITLE
Fix for SU2_DEF with periodic boundaries.

### PR DESCRIPTION
**Pull request by talbring**
I tried to fix the problem with FFD and periodic boundaries. Would be good if someone could have a look at this solution.

PS: WRT_HALO still has to be enabled in the config file in order to work.

### CODE REVIEW

**Comment by economon** [comment]
Thanks, Tim. The code changes look ok to my eye, but I don't have a test case handy to run this through. Perhaps you or Salvo have one available to test?

**Comment by talbring** [comment]
I have tested it only on a 2D case. So maybe we should wait until we have a working 3D periodic case.

**Comment by salvovitale** [comment]
Yes Tom, we also have a 3D case to test! We will keep you posted on it!!

**Comment by talbring** [comment]
Next pull request will include this along with other fixes.

**Pull request closed without merging**
