### PR TITLE
Update catch.hpp to v2.13.9

### PR DESCRIPTION
**Pull request by bigfooted**
## Proposed Changes
*Give a brief overview of your contribution here in a few sentences.*
updated catch.hpp from the catchorg github repository

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [X] I am submitting my contribution to the develop branch.
- [X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [ ] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by bigfooted** [comment]
license did not change, so no need to update that file.

**Review by pcarruscag — APPROVED** [review]
LGTM

**Comment by eli-schwartz** [comment]
I wonder if maybe it would be a better idea to delete this (and other stuff) from externals/ and add it to subrojects/ instead. You can use `meson wrap install catch2`, and it's a simple ini file to vet instead of an 18k line file. git diffs become a lot simpler too.

**Comment by pcarruscag** [comment]
It's a bit more involved because we want to support "offline" mode. But that's what we do with dependencies that we cannot copy due to license restrictions.

With that said Nijso has probably fought enough with unit tests for the rest of the year, so if you want to send a pull request our way you are most welcome :)
Cheers

**Comment by eli-schwartz** [comment]
Offline mode could be done by creating source code tarballs as release artifacts instead of using github's autogenerated archives.

Meson has a built-in tool for this, which automatically includes offline copies of used subprojects: `meson dist --include-subprojects`
See https://mesonbuild.com/Creating-releases.html#include-subprojects-in-your-release

**Pull request merged**
