### PR TITLE
Feature small makefile update

### PR DESCRIPTION
**Pull request by hlkline**
The manual changes in this branch are in the Makefile.am file; the Makefile.in files are generated by automake. 
This makes a slight change to the SU2_SOL makefile reducing the number of objects that are compiled - it was previously recompiling several of the SU2_CFD/ files. It appears to be necessary for SU2_SOL to recompile the solver_structure file (otherwise an error appears).

### CODE REVIEW

**Comment by hlkline** [comment]
FYI, since automake was run with v1-14 please wait to merge until I have a chance to re-do the makefiles with v 1-12

**Comment by economon** [comment]
Thanks, Heather.

I've seen some weird behavior when running "$ make distclean" on the current develop (without this change). I think the issues are also related to the SOL files. Have you seen this problem, or will this possibly fix it? If no, I'll look into it more.

**Comment by hlkline** [comment]
It might fix some of it? I think that make distclean will be looking for
all the build files; so anything that was built twice might cause something
weird since distclean would try to clean it twice. There is still one file
for SOL that is rebuilt, so some part of distclean might be helped by this
commit - but I suspect not all. I will try this myself too.


On Mon, Feb 8, 2016 at 1:00 PM, Thomas D. Economon <notifications@github.com
> wrote:

> Thanks, Heather.
>
> I've seen some weird behavior when running "$ make distclean" on the
> current develop (without this change). I think the issues are also related
> to the SOL files. Have you seen this problem, or will this possibly fix it?
> If no, I'll look into it more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/su2code/SU2/pull/235#issuecomment-181536988>.
>



-- 
Heather Kline
NASA Space Technology Research Fellow
PhD Candidate, Aeronautics & Astronautics, Stanford University
BS Aerospace Engineering, Rensselaer Polytechnic Institute
kline.hl@gmail.com, hlkline@stanford.edu

**Comment by economon** [comment]
Aok. Thanks for checking that. Let's see if we can figure out a workaround on this pull request to get everything sorted. Having the autotools versioning all lined up is very important for portability, and distclean is very handy when you're working with the AD build.

**Comment by economon** [comment]
Thanks for getting this sorted, Heather. Merging now...

**Pull request merged**
