### PR TITLE
Fix duplicated entry of CFL_ADAPT_PARAM

### PR DESCRIPTION
**Pull request by joaofl**
Example was not running due to AssertionError: Config file has multiple specifications of CFL_ADAPT_PARAM
Duplicated entry of CFL_ADAPT_PARAM removed

### CODE REVIEW

**Comment by talbring** [comment]
Thanks, I'll merge that in.

**Comment by joaofl** [comment]
@talbring 
when I run 

`parallel_computation.py -f turb_ONERAM6.cfg -n 8
`
I get errors due to three other configuration parameters, which I had to comment out to be able to run this example. These are:

```
SOLUTION_LIN_FILENAME: invalid option name. Check current SU2 options in config_template.cfg.
RESTART_LIN_FILENAME: invalid option name. Check current SU2 options in config_template.cfg.
SURFACE_LIN_FILENAME: invalid option name. Check current SU2 options in config_template.cfg.
```
Are this lines supposed to be there? I'm not sure, reason why I'm letting you know.

**Comment by talbring** [comment]
Are you sure you're using the config file that corresponds to the current develop or master ? Because I don't see these options in TestCases/rans/oneram6/turb_oneram6.cfg

**Comment by joaofl** [comment]
@talbring  Sorry for not being more specific. The example file is actually into
`TestCases/optimization_rans/pitching_oneram6/turb_ONERAM6.cfg`

If this configs are actually not supposed to be there, I could make a pull request removing them.

**Comment by talbring** [comment]
I see, I guess somebody forgot to remove these. You can open a pull request if you want :)

**Comment by joaofl** [comment]
Done: https://github.com/su2code/SU2/pull/392

**Pull request merged**
