### PR TITLE
Feature mixingplane2d

### PR DESCRIPTION
**Pull request by salvovitale**
With this branch some turbomachinery capabilities have been added to the code. The main features are:
-Supersonic outlet Non Reflecting BC
-Conservative and Non-Conservative 2D Mixing-Plane Interface
-2D Turbomachinery performances calcualation for single blade, stage and multi-stage geometry. This will be soon used to derive a Discrete Adjoint using as OF turbomachinery performance.
- restart_file for multizone flow simulation  

I ve created a turbomachinery folder in the TestCase folder with two new testcases in which these new capabilities can be tested.

cheers

sv

### CODE REVIEW

**Comment by talbring** [comment]
There is a missing replacement of double in solver_direct_mean.cpp:7270 and maybe you could replace the copysign function in solver_direct_mean.cpp:8229. Then it should compile without errors.

**Comment by salvovitale** [comment]
I ll do it immediately!!!
Thanks Tim!!!

**Comment by salvovitale** [comment]
Hey Tom (@economon) the compilation issue has been solved. Regression test went well. I am waiting for the merge to the develop, so that I can open the branch feature_turboSU2 as discussed yesterday, and add also regression test for the new testcases in the folder turbomachinery.

cheers

sv

**Comment by economon** [comment]
Yep, things seem to be passing just fine now, and it looks like things are coming along nicely for the turbomachinery features.

Before we merge this in... I am a little concerned with the number of additions to solver_direct_mean.cpp related to the different switch statements and subroutines needed for the Riemann and non-reflecting BCs. Is there anything we can do to simplify things?

In addition, could you please clean up the spacing/style in those methods to match up with the other BCs (more comments are needed, indentation, variable declarations, etc.)? It would also be great to have a little more detail on how to use the new BCs in the descriptions in config_template.cfg. Thanks!

**Comment by salvovitale** [comment]
Hey @economon  as we agreed I clean up and formatted the code,  and add some comments to make the code more readable.

cheers!

sv

**Comment by economon** [comment]
Thanks for cleaning things up, Salvo. I just fixed up some issues on this pull request due to other activity in develop that was in conflict. I would recommend that you give this new version a try with your own tests when you have a chance.

Once the checks pass, we'll merge this into develop.

**Pull request merged**
