### PR TITLE
Feature FSI FEA

### PR DESCRIPTION
**Pull request by rsanfer**
Dear all,

as many of you know, we have been working for quite a while in the development of the FSI solver within SU2. So far, we have been using a separate branch; however, this branch has grown quite big (almost 200 commits!) and it's probably time to merge it with the develop branch. This way, other folks can start using the new code infrastructure for multi-physics problems, while reducing the hassle for everyone in future pull requests from our side. 

This pull request includes, among others:

1. Multi-physics support and improvements: 
  - CTransfer structure with MPI support for parallel multi-zone simulations.
  - CTransfer subclasses for physical definition of multi-physics interaction variables.
  - CInterpolator structure with support for interpolation algorithms.
2. A FEM structural solver aiming to deal with geometrical and material nonlinearities.
3. A BGS driver structure for FSI problems.
4. General bug fixes and improvements for unsteady problems with dynamic meshes.
5. New configuration options required for the different kinds of problems tackled.

If all the tests pass, I will add some regression tests, once the mesh files and solution files have been added to the TestCases repository.

Please note that this version of the code is still under development, and we are currently working on further improvements in the efficiency and the capabilities of the solver. We intend to include these further developments by the time of the next release of the code. 

Cheers,

Ruben

### CODE REVIEW

**Comment by talbring** [comment]
Great contribution! Thanks for sharing.

I just did a quick fix of the file permission.

**Comment by economon** [comment]
Thanks for the quick fix, Tim. 

Kudos to Ruben and Heather for all of the exciting contributions packed in this pull request: this is the culmination of months of hard work on their sides, and the collaboration has been very fruitful (just count the commits!).

The tests are passing now, but I have one small request before we merge everything. If you check out the details of the build in Travis CI, there are many warnings. Can you please clean these up? They are mostly unused variables and the like. Otherwise, things are looking pretty good to me...

**Comment by hlkline** [comment]
I think several of those warnings are from my end, I will take a look at them shortly.

**Comment by rsanfer** [comment]
Thanks very much Tim, Tom and Heather for the help!

There are a couple of warnings more in CFEASolver::SetFEA_Load_Int, I will take care of them.

Also, Tom, if you want to go ahead and push the meshes into TestCases/develop, I can include the regression tests before we merge, and we do all at once.

**Comment by economon** [comment]
Thanks for adding the tests. Looks good to me! Merging now...

Keep up the excellent work.

**Pull request merged**
