### PR TITLE
Fix #1081

### LINKED ISSUE #1081: Latest version of develop does not build in debug mode
**Describe the bug**
The latest version of develop gives undefined references when building in debug mode, e.g.
undefined reference to `CRoeBase<CRoeScheme<CCompressibleViscousFlux<2ul> >, CCompressibleViscousFlux<2ul> >::nVar'

**To Reproduce**
Build the debug version with meson using --buildtype=debug

**Desktop (please complete the following information):**
 - OS: Ubuntu 18:04
 - C++ compiler and version: g++ 8.4.0
 - MPI implementation and version: OpenMPI version 2.1
 - SU2 Version: [e.g., v7.0.6]

### PR DESCRIPTION
**Pull request by pcarruscag**

### CODE REVIEW

**Review by vdweide — CHANGES_REQUESTED** [review]
It works for me now in combination with both the GNU and Intel compilers. However, for Intel I get a ton of warnings the type 

warning #2196: routine is both "inline" and "noinline"

I'm not sure if these are only caused by your changes, but this is not what we want, I suppose.

Also I get the following warning with Intel
 ./Common/src/CConfig.cpp(4666): warning #823: reference is to variable "iMarker" (declared at line 3174) -- under old for-init scoping rules it would have been variable "iMarker" (declared at line 4662)

This has come in an earlier PR, but can be fixed easily by removing the unsigned short in line 4662.

Finally, when I build the AD version the Intel compiler gives the following warnings

warning #16219: Some OpenMP processing was skipped to constrain compile time. Consider overriding limits (-qoverride-limits).

./SU2_CFD/include/numerics_simd/flow/convection/centered.hpp(182): warning #15552: loop was not vectorized with "simd"

Adding -qoverride-limits does increase compile and link time significantly, but it does not solve the problem. These warnings seem to be caused by the template classes in the following two files.

SU2_CFD/include/numerics_simd/flow/convection/roe.hpp
SU2_CFD/include/numerics_simd/flow/convection/centered.hpp

I don't know whether you have vectorization in mind in combination for the AD version, but then it may be useful to split up these files, if possible.

I do not have access to a Mac, so I didn't test if on OSX.

**Comment by pcarruscag** [comment]
My proposal the other day seems to have put you in quite the mood...
Do you also get a ton of "-1 converted to unsigned short"? Or is that just me?
I'll see what I can do about the rest.

> I do not have access to a Mac, so I didn't test if on OSX.

I tried clang 6 and clang 10, and had to stupefy the code because of the former, should be ok on Mac

**Comment by vdweide** [comment]
I feel a bit guilty indeed regarding the review of the PR's.

I didn't see the -1 conversion warning, but I may have missed them because of all the other warnings. Do you get these from the Intel compiler as well?

**Comment by pcarruscag** [comment]
Exclusively from the Intel compiler, I think, they've been around for a while now, hence my not caring much about Intel warnings.

**Comment by pcarruscag** [comment]
Ok that's all I can do. There are so many warnings on AD builds with the Intel compiler (and also with gcc-10) that I don't see the point in wasting more time.

**Review by vdweide — APPROVED** [review]
I don't get any warnings GNU version 10 and also for intel the number of warnings are significantly less now.

**Pull request merged**
