### PR TITLE
Deprecating OPT_OBJECTIVE

### PR DESCRIPTION
**Pull request by hlkline**
This is a relatively small code change, but the change in options will effect the config files for everyone currently using optimization, and for anyone who has an OPT_OBJECTIVE defined in their config file. 

The reasoning behind deprecating this option:
-Compressing the OPT_OBJECTIVE and OBJECTIVE_FUNCTION options into a single specification will reduce potential confusion about the behavior of these options. 
-Using the new OBJECTIVE_WEIGHT option to specify not only the scaling but also the sign clarifies the behavior of the optimizer - previously, the sign of the objective function was automatically flipped behind the scenes, now this is controlled by the user.
- This change facilitates planned further modifications to allow multiple objectives. 

Please feel free to comment both on the code changes themselves as well as on the new config option format

### CODE REVIEW

**Comment by economon** [comment]
Heather: I know we talked about this one in person the other day, but I am still weighing things... Even though it looks like a small change, it's a really big one, and I want to make sure we keep things as clear and user-friendly as possible. 

If anyone else has thoughts on this, please feel free to chime in. Maybe we can catch up about it again early this week.

**Comment by hlkline** [comment]
I agree - and there's certainly more than one way to do things in this case. 
I second your call for others to chime in on this.

**Comment by talbring** [comment]
I think its a good idea to separate the weight from the objective function. This makes it more clear and flexible.  However, what bothers me a little bit is that the OBJECTIVE_FUNCTION option is now used for two things. Namely for the optimization and for the individual adjoint runs. Maybe it would be good to still have another option for specifying the obj. function for the adjoint run itself (with a completely different name, so that there won't be any confusions). 

Maybe it's less of a problem then I think, though.

**Comment by hlkline** [comment]
Thanks for your input, I think you make a good point. 

The way I was thinking about it is that OBJECTIVE_FUNCTION would now serve the same purpose and have the same behavior across multiple methods - right now (in the current develop and master branch), OBJECTIVE_FUNCTION is used either when running SU2_CFD with the continuous or discrete adjoint method, and when running continuous_adjoint.py, while OPT_OBJECTIVE is used with shape_optimization.py.
Where this gets confusing is that shape_optimization.py automatically flips signs of certain objectives without ever informing the user that this is the case - right now the only way to find out that the sign is flipped is either to carefully read through the source code or run a case and figure it out from the results. 
This will get more confusing when adding in multiple objectives - I would like to at least move the sign change into the config file rather than hidden behind the scenes; however that does get dangerous as it will quietly change the optimization behavior for people who aren't aware of that modification.

**Comment by fpalacios** [comment]
Sorry for my late reply and thanks Heather for opening this important discussion.
I fully agree with you and OBJECTIVE_FUNCTION and OPT_OBJECTIVE cause confusion.

As far I see the problem, if we focus on a typical users point of view, I think that OPT_OBJECTIVE and OPT_CONSTRAINT must be in the config file and as close as possible. They are the key to define an optimization problem (one of the key features of SU2). On the other hand, as you suggested we need to add some flexibility. It would be interesting to to able to define a multi-objective like
OPT_OBJECTIVE= DRAG * DRAG_WEIGHT; LIFT^2 * LIFT^2_WEIGHT;

As Tim pointed out OBJECTIVE_FUNCTION is important because is what we use to play and develop the adjoint capability but, from the users point of view it is not as interesting as the OPT_OBJECTIVE. If everything works ok, OPT_OBJECTIVE should be enough for most of the SU2 users. How many typical users are interested in solving and adjoint problem for the sake of solving of an adjoint problem?

However OBJECTIVE_FUNCTION is not a good name, from the point of view of the continuous adjoint, I would feel comfortable if we change it to ADJ_BND_CONDITION. That probably doesn't work for the discrete adjoint, isn't it? Tim, What key word would work for the Discrete Adjoint? We need something that reflect the effect, in mathematical terms, of the objective function in the AD adjoint problem.

Finally, before adding any capability we should ask ourself how general is going to be and if it going to be useful for the most part of the SU2 users community (in my opinion, external aerodynamics). If the new objective function is only useful for us, or a research project, then I think we need to create some kind of custom objective function, (e.g. CUSTOM_OBJFUNC at the same level than DRAG, LIFT, etc) that we can describe with other set of parameters.

Thanks,
Francisco

**Comment by juanjosealonso** [comment]
All,

Following this discussion, why not use something more descriptive for OBJECTIVE_FUNCTION?  At the end of the day, it is meant as the functional, derived from the solution of the PDE, that we are solving the adjoint equations for. Then we use that adjoint field to compute gradients.  How about ADJOINT_FUNCTIONAL?  Or ADJ_FUNCTIONAL?

Best,

Juan

On Feb 22, 2016, at 8:34 AM, Francisco Palacios <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for my late reply and thanks Heather for opening this important discussion.
I fully agree with you and OBJECTIVE_FUNCTION and OPT_OBJECTIVE cause confusion.

As far I see the problem, if we focus on a typical users point of view, I think that OPT_OBJECTIVE and OPT_CONSTRAINT must be in the config file and as close as possible. They are the key to define an optimization problem (one of the key features of SU2). On the other hand, as you suggested we need to add some flexibility. It would be interesting to to able to define a multi-objective like
OPT_OBJECTIVE= DRAG * DRAG_WEIGHT; LIFT^2 * LIFT^2_WEIGHT;

As Tim pointed out OBJECTIVE_FUNCTION is important because is what we use to play and develop the adjoint capability but, from the users point of view it is not as interesting as the OPT_OBJECTIVE. If everything works ok, OPT_OBJECTIVE should be enough for most of the SU2 users. How many typical users are interested in solving and adjoint problem for the sake of solving of an adjoint problem?

However OBJECTIVE_FUNCTION is not a good name, from the point of view of the continuous adjoint, I would feel comfortable if we change it to ADJ_BND_CONDITION. That probably doesn't work for the discrete adjoint, isn't it? Tim, What key word would work for the Discrete Adjoint? We need something that reflect the effect, in mathematical terms, of the objective function in the AD adjoint problem.

Finally, before adding any capability we should ask ourself how general is going to be and if it going to be useful for the most part of the SU2 users community (in my opinion, external aerodynamics). If the new objective function is only useful for us, or a research project, then I think we need to create some kind of custom objective function, (e.g. CUSTOM_OBJFUNC at the same level than DRAG, LIFT, etc) that we can describe with other set of parameters.

Thanks,
Francisco

**Comment by hlkline** [comment]
I agree with both of you, that OBJECTIVE_FUNCTION should be a bit more descriptive. 
Following the format of other adjoint options (CONV_NUM_METHOD_ADJFLOW, LIMIT_ADJFLOW), how about OBJFUNC_ADJFLOW or FUNCTIONAL_ADJFLOW? 

Regarding the format of OPT_OBJECTIVE, what I have working in another branch (which I have been sitting on pending figuring out these types of issues and more testing) is a format like:
OPT_OBJECTIVE = DRAG*0.1; LIFT*2.0
COMBINE_OBJECTIVE = YES
Where the associated adjoint settings are:
OBJECTIVE_FUNCTION = DRAG, LIFT
OBJECTIVE_WEIGHT = 0.1, -2.0

The effect of COMBINE_OBJECTIVE is a flag to switch between treating the objectives separately (each objective and its gradient is evaluated separately and the python scripts loop sequentially over the objectives, or if this option is 'YES' then a 'COMBO' value is output to the history file and the gradient is computed all-at-once (I can explain that more offline if necessary)). At the moment this only works for linear combinations of existing objectives, so the sample objective Francisco listed would be beyond that. 

What do you think of this as an option structure for minimizing 0.1*DRAG-2.0*LIFT:
OPT_OBJECTIVE = COMBINATION
...
OBJFUNC_ADJFLOW = COMBINATION
..
COMBO_OBJDEF = DRAG, LIFT
COMBO_OBJWEIGHT = 0.1, -2.0
Where this would still be compatible with looping over sequential objectives in the shape optimization  (that is really just a fairly small update to the python, and has some benefits depending on how many constraints you have), and both the adjoint and optimization would refer to OBJDEF if 'COMBINATION' is set as the objective.

**Pull request closed without merging**
