### PR TITLE
Feature general ffd

### PR DESCRIPTION
**Pull request by talbring**
This pull request features some improvements regarding the FFD. To be more precise:

- It is now possible to allow the FFD control points to move in an arbitrary direction. This is automatically enabled if the direction of movement in the design variable definition is set to (0.0,0.0,0.0). The set_ffd_design_var.py is updated accordingly (you can now specify the direction, default is 0.0). At the moment this is only possible for the discrete adjoint. But it could also be extended to the cont. adjoint.
- Along with this goes a refactoring of SU2_DOT to reduce code copy.

Especially for the optimization of turbine blades and everything else that is not an airfoil this might be useful.

### CODE REVIEW

**Comment by economon** [comment]
Thanks, Tim. Adding flexibility to the FFD is a great contribution. I was just going through the changes and I have a couple of questions:

1. I noticed that you have added AD as an option for computing the geometric sensitivity component (change in the surface location due to a delta change in the design variable) that multiplies the adjoint sensitivity. Is there a way to make this usable for the continuous adjoint too rather than using finite differencing? This assumes that the user has built the AD version, even though they use the continuous adjoint.

2. On a related note (I think), is the finite differencing that is currently used for computing the geometric sensitivity the only roadblock to arbitrary FFD movements for the continuous adjoint?

**Comment by talbring** [comment]
Thanks for your remarks. I already named the routines AD/FD to prepare for that. With an appropriate config option this also works then for the cont. adjoint. I'll try that first before merging.

**Comment by talbring** [comment]
I added the option AUTO_DIFF=YES/NO to use the AD based projection also for the cont. adjoint. If you use SU2_DOT_AD then it is enabled by default. So setting using this config option is only required if you run the python scripts, since we need to determine somehow what binary should be called (SU2_DOT or SU2_DOT_AD).

**Comment by economon** [comment]
Thanks for the addition of AD for computing the geometric sensitivity in the continuous case. Looks good to me. I'll merge this request in now.

**Pull request merged**
