### PR TITLE
Add HDF5 backend support for CGNS in SU2

### PR DESCRIPTION
**Pull request by MicK7**
## Proposed Changes
*Give a brief overview of your contribution here in a few sentences.*
 The proposed changes consist in providing an hdf5 enabled cgns library inside SU2.
This is done by embedding the needed hdf5 sources inside the cgns directory.
A basic meson.build file helps with compilation (instead of original cmake).

## Related Work
None

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [x] My contribution is commented and consistent with SU2 style.
- [x] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by MicK7** [comment]
The branch can be tested by converting an existing testcase cgns file to hdf5.

**Comment by MicK7** [comment]
It seems that LGTM analysis is using a very old version of meson. Can someone update it ?

**Comment by pcarruscag** [comment]
Thanks for the update @MicK7, this only affects code in externals right? if so there is no need to worry about LGTM, I think it was using the old build system.

**Comment by MicK7** [comment]
@pcarruscag yes all the modification are in external. It is just that the LGTM C++ if failing because it is too old and can't cope with cmake syntax. Since I mainly copy pasted the source of hdf5 without modification, I don't really want to modify them for maintainability.

**Comment by MicK7** [comment]
My request too update the meson used by LGTM C/C++ is to not create issue for other PR is this one goes in.

**Review by pcarruscag — APPROVED** [review]
Yep I got that, I was asking to know if I should look at any of the 531 files :smile: 
LGTM seems fixed.

**Comment by pcarruscag** [comment]
Does this support a type of CGNS that we didn't before? If so can you add a small test?

**Comment by MicK7** [comment]
@pcarruscag I can change one of the existing testcases to have a validation

**Comment by jtlau** [comment]
I'm having an issue compiling on macOS. I get an error after "./meson.py build":

`Configuring H5pubconf.h using configuration

externals/cgns/hdf5/meson.build:662:0: ERROR: #mesondefine does not contain exactly two tokens: #cmakedefine H5_HAVE_WINDOWS @H5_HAVE_WINDOWS@`

I'm not sure where to go from there... since I don't need cgns I workaround this by disabling it...
LMK if you need the full configure error

**Pull request merged**
