### PR TITLE
[WIP] Removing turbomachinery legacy output

### PR DESCRIPTION
**Pull request by joshkellyjak**
## Proposed Changes
Transferring turbomachinery outputs from legacy format to current format
 

## Related Work
*Resolve any issues (bug fix or feature request), note any related PRs, or mention interactions with the work of others, if any.*

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [ ] I am submitting my contribution to the develop branch.
- [ ] My contribution generates no new compiler warnings (try with --warnlevel=3 when using meson).
- [ ] My contribution is commented and consistent with SU2 style (https://su2code.github.io/docs_v7/Style-Guide/).
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp), if necessary.

### CODE REVIEW

**Review by pcarruscag — COMMENTED** [review]
Thank you for starting this work. I have started the work to remove the legacy output, and in that process I will remove the turbomachinery driver by moving the extra functions to the single and multizone drivers.
Is it possible for you to add the turbo outputs to CFlowOutput instead of using a dedicated class?

**Comment by joshkellyjak** [comment]
No worries, glad to be of assistance. I can move to CFlowOuput, that is fine. I'm going to keep making my way through this task over the week and we can discuss at dev meeting on 11th?

**Comment by pcarruscag** [comment]
Sounds good, I hope to have something working by then.

**Comment by joshkellyjak** [comment]
Updated name of PR to reflect requested changes

**Comment by pcarruscag** [comment]
Maybe we can chat in the developer meeting today at 4pm CET (in 2.5h) https://meet.jit.si/SU2_DevMeeting it looks like this is becoming harder than it needs to :sweat_smile:

**Comment by joshkellyjak** [comment]
Sounds good, see you then

**Comment by pcarruscag** [comment]
see #2003

**Pull request closed without merging**
