### PR TITLE
Added missing area/volume objective functions in option_structure.hpp

### PR DESCRIPTION
**Pull request by talbring**
At the moment it is not possible to have an area/volume constraint for the shape optimization. SU2_GEO simply exits with an error because OBJECTIVE_FUNCTION=AREA/VOLUME is missing in the objective function definition. This pull request simply adds them. Maybe someone removed them accidentally. If it was intentionally then we should also remove the thickness entries and modify the python scripts accordingly.

### CODE REVIEW

**Comment by hlkline** [comment]
Hi Tim
Thanks for taking action on this - some folks on the forum had noticed related issues with one of the tutorials, and I agree, that either all the geometric functions should be on that list, or none of them.
From what I can tell, SU2_GEO appears not to use the objective_function option at all.

One potential solution would be to get the python scripts to set some default value to objective_function for all the geometric functions. Unfortunately I don't have the time to test that out fully right now, do you have the time to look into that?

The tutorial that was having issues was "Constrained Optimal Shape Design of a Fixed Wing".

**Comment by talbring** [comment]
Hi Heather,

the problem is this code section (eval/gradient.py):

`def gradient( func_name, method, config, state=None ):    
`
...
 ```
if (type(func_name)==list):
        if (config.OPT_COMBINE_OBJECTIVE=="YES"):
            config.OBJECTIVE_FUNCTION = ', '.join(func_name)
            func_name_string = 'COMBO'
        else:
            func_name = func_name[0]
            config.OBJECTIVE_FUNCTION = func_name
    else:
        config.OPT_COMBINE_OBJECTIVE="NO"
        config.OBJECTIVE_FUNCTION = func_name
        config.OBJECTIVE_WEIGHT = "1.0"
```

Here the `config.OBJECTIVE_FUNCTION` is set also for the geometric functions. This is probably why it only occurs in v4.3 ... Previously, in older versions, this value was not set or there was some other non-geometric function set when calling SU2_GEO. I think my solution is more like a workaround and we should find a more consistent way (like removing the geometrical things from the objective function list in option structure altogether).

**Comment by economon** [comment]
Hi Tim, Heather: yes, this is an important issue to clear up before releasing v5 this week. Let's use this PR to fix the issue (even if just short term), and we'll find a better long term solution.

I'm taking a look at this now too.

**Comment by hlkline** [comment]
I think I found a quick fix, that I will be pushing to this branch shortly; feel free to revert and/or improve on it.

**Comment by economon** [comment]
Great, thanks for the help, Heather. Please do push the fix, and if you have a minute, can you please check that the tutorial is working with your changes?

**Comment by economon** [comment]
@hlkline: looks like your last commit fixed the tutorial issue with the ONERA M6 case for me. Thanks! Are you happy with this after your latest commit here to this branch, or do you still have some changes to push?

**Comment by hlkline** [comment]
@economon all good from my end.

**Comment by talbring** [comment]
Should I remove the AREA and VOLUME then from the objective function list again ?

**Comment by economon** [comment]
Tim, yes, looking back, I do not believe those were ever in the option list for the C++. If you have a minute, can you please remove? We'll merge this fix in very soon too. Thanks!

**Comment by talbring** [comment]
Also ready to be merged! Thanks Heather for fixing this.

**Pull request merged**
