### PR TITLE
Add an option to meson for extra dependencies (to fix mpich and lapack issues)

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
Add option `-Dextra-deps=a,b,c` to meson to provide a simpler work around for build problems with MPICH and LAPACK.
For example if you have MPICH but it is not detected (because its pkg config name is not "mpi" but "mpich" instead), you would do `-Dcustom-mpi=true -Dextra-deps=mpich`.
If you have linker errors because the blas library does not contain LAPACK functions, you would do `-Dextra-deps=lapack`.
The option takes a comma-separated list.

I will update the documentation once this goes through.

## Related Work
#991
#1000

## PR Checklist
- [X] I am submitting my contribution to the develop branch.
- [X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [X] My contribution is commented and consistent with SU2 style.
- [X] I have added a test case that demonstrates my contribution, if necessary.
- [X] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by vdweide** [comment]
Looks good to me, but it would be nice to have the examples you mention above somewhere in the documentation. From the description in meson_options.txt I would not be able to figure it out.

**Comment by pcarruscag** [comment]
Thanks Edwin, the plan is to update the build instructions on the website before the release.

**Comment by pcarruscag** [comment]
@CatarinaGarbacz this should fix the compilation issues with Eigen

**Review by vdweide — APPROVED** [review]
Looks all good to me then.

**Pull request merged**
