### PR TITLE
Call SetSurface_... 

### PR DESCRIPTION
**Pull request by FlorianDm**
Those Set functions need to be called at least for the Get functions in CEulerSolver::Evaluate_ObjFunc unless they are supposed to be called somewhere else.

These calls exist in the legacy output and seem to have been removed because SetHistoryOutputPerSurfaceValue is replacing them for the history/screen output.

Perhaps this will be redundant when #913 is done

### CODE REVIEW

**Comment by talbring** [comment]
Hi @FlorianDm 

thanks for fixing this. We can merge this in for the moment. Note however that I'm reworking at the moment how all of the objective functions are defined in #913.

**Comment by FlorianDm** [comment]
Hello @talbring 

Yess really looking forward to the result of your work!

**Comment by economon** [comment]
Also, we're happy to give regular contributors direct access to the repository (easier to collaborate and participate in reviews, etc.). Just let me know if you would like to be added.

**Comment by FlorianDm** [comment]
@economon it would be a privilege ;)

**Pull request merged**
