### PR TITLE
cleaning up config_template.cfg issue #682

### PR DESCRIPTION
**Pull request by WallyMaier**
This pull request addressed issue #682 and cleans up the config structure.

- [x ] I am submitting my contribution to the develop branch.
- [ x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [ x] My contribution is commented and consistent with SU2 style.

### CODE REVIEW

**Comment by WallyMaier** [comment]
This is fixing the template, not config_template......

**Comment by jtlau** [comment]
Thanks for cleaning up the config template. As far as I can tell, the Dirichlet and Neumann boundary conditions (around line 650) are not implemented in SU2 (they exist as placeholders). If this is true, keeping them in the config_template would be misleading. 

Leaving this as a comment since I don't know if those markers are useful in places I haven't seen (like outside of SU2_CFD). Can someone confirm?

**Comment by economon** [comment]
@jtlau : you are correct that these are not currently in use. I believe BC_Dirichlet() and BC_Neumann() had been used in older solvers that have since been removed or updated (the wave solver comes to mind), but they are now just the empty hooks in case somebody would like to implement them for a solver in the future.

**Comment by WallyMaier** [comment]
@economon should the options in config template be removed then?

**Comment by marcovanderbijl** [comment]
new issue #687 also involves config_template.cfg cleanup

**Comment by marcovanderbijl** [comment]
in config_template.cfg
FFD_Definition = (...)
needs to be placed somewhere in front of 
DV_PARAM= ( ...)

currently it is the other way around and this results in a parsing error:
DV_PARAM: undefined design variable type found in configuration file.

maybe I should make a new issue out of this,.. I dunno what the procedure is?

**Comment by WallyMaier** [comment]
addressed issue #688

**Pull request merged**
