### PR TITLE
Time coefficient in classical RK4 explicit

### PR DESCRIPTION
**Pull request by leminhman0312**
## Proposed Changes
For classical RK4 explict, arent the time coefficients suppose to go (1.0, 0.5, 0.5, 1.0)?  The functional step are correct as (1/6, 1/3, 1/3, 1/6).  I couldnt use the explicit RK4 on the tutorial to test this because it says SU2 diverges. 
 

## Related Work
Modified time coefficient in classical RK4

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [x] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by pcarruscag** [comment]
I think the coefficients are correct. Do you have a reference?

**Comment by leminhman0312** [comment]
I juse use this to look up the formula for rk4 explicit.  Aren the time coefficients used to do: ti, ti+1/2, ti+1/2, ti+ h for k1, k2. k3 and k4?

**Comment by economon** [comment]
Hi @leminhman0312 : we are using a low-storage implementation of RK4 that only requires two storage locations (old & new). I think that, if you multiply out what you see in CEulerSolver::Explicit_Iteration() for the RK4 option, you will see that is should match the standard formulas. Can you give it another look (always good to verify these things)?

**Comment by pcarruscag** [comment]
On the first step (iRKstep=0) the residual (k1) was evaluated for the current solution (y) we then set the solution as y+0.5*k1 (via nodes->AddSolution) so that on the next call (iRKstep=1) k2 is computed.
We keep 3 states, SolutionOld (y), Solution (y+ci*ki), and SolutionNew (y(t+h)) which is built incrementally until it replaces Solution on the last step.

**Comment by leminhman0312** [comment]
Thank you @pcarruscag  and @economon for clarifying.  I understood it better now.

**Pull request closed without merging**
