### PR TITLE
Various fixes II

### PR DESCRIPTION
**Pull request by oleburghardt**
## Proposed Changes
This is a follow-up of #798 for minor changes. 
Feel free to add bug fixes and similar for problems that you might came across during testing.

## PR Checklist
- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [x] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by oleburghardt** [comment]
@pcarruscag 
Maybe you can add the fix for the issue that you brought up this morning to this branch?

**Comment by WallyMaier** [comment]
@oleburghardt I can run through the branch and do some general cleanup (commente, whitespaces and such), unless you think it would be better to in its own branch

**Comment by pcarruscag** [comment]
@WallyMaier let's keep that for when we move files around, unless you are talking about some completely wrong comments, as it tends to create a lot of merge conflicts.

**Comment by WallyMaier** [comment]
@pcarruscag I was planning to do all, but I can stick to places that files have already been moved around.  Is there a list of future restructuring to happen so I can avoid those files?

Version 7 seems to be a good place to tackle a lot of these small changes. In any case, I can address this in a separate branch to limit any downsides.

**Comment by pcarruscag** [comment]
I have CSolver and CNumerics in mind for restructuring as part of #789 after #790 and #777 are merged.
Maybe you could start with geometry classes (they sure have plenty of formatting issues)? It does not seem like anyone is working on them. I noticed some trailing spaces in the new output structure too.

**Pull request merged**
