### PR TITLE
Fix complex ad

### PR DESCRIPTION
**Pull request by talbring**
This pull request fixes the issue #319. Already includes the codi update #350. Would be better to merge the latter first though.

### CODE REVIEW

**Comment by talbring** [comment]
Forgot to mention it, we checked it already on OSX (we found someone with a macbook :)) here and it works. But I would of course appreciate it if other people can give it a try!

**Comment by sravya91** [comment]
Thanks for fixing this Tim! I compiled on my Mac too and it looks good to
me. I think we can merge it in and remove the flag for HB and include its
regression test.

**Comment by talbring** [comment]
Of someone could also run the regression tests (or at least the HB tests) on a mac that would be even better (maybe you did this already @sravya91?)!

**Comment by sravya91** [comment]
Tim,

The HB regression test residuals are off and the simulation diverges as of
now. I'll take a closer look at it asap. Let's wait for merging it in until
then.

Sravya

**Comment by talbring** [comment]
There was an error in the division operator :) can you try it again ?

**Comment by sravya91** [comment]
Ah, that fixed the issue then. The HB regression test passes now. We can
merge it in.

**Comment by economon** [comment]
Great! Assuming they pass the tests, please go ahead and merge in #350 and then this (#351).

**Comment by talbring** [comment]
Thanks, merging this in then.

**Pull request merged**
