### PR TITLE
Added compatibility for Windows systems

### PR DESCRIPTION
**Pull request by ArneBachmann**
Until now we have always patched the interface.py by hand to make it run on Windows Server 2012 R2.
By issueing a PR we hope this won't be necessary in the future anymore.

### CODE REVIEW

**Comment by hlkline** [comment]
Thank you for submitting this pull request. 
Please modify this to be based off and merged into the develop branch, rather than the master branch. The travis system will then automatically run the regression tests, and we can proceed from there. 

Just a question: what effect does this have in windows 64 bit versions? It looks like this would only effect windows 32 bit, is that correct?

**Comment by hlkline** [comment]
As an added note: if you find in the future that you have to make a small modification to every version, but do not want to make a pull request, you can use what is called a 'git patch' which will automatically make such your updates to the new version. 

This change looks like it might fix problems for other users, and not break anything for those on other systems, so I think this is a good topic for a pull request, it just needs to be sent into the develop branch rather than the master branch. 

Some directions on making patches:
https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/

**Comment by ArneBachmann** [comment]
"win32" is a marker valid for all Windows installations since XP, I guess. We have 64bit Servers and still we get "win32".
The entire code base looks like it could use a good overhaul, especially regarding formatting, but also the call hierarchy and naming. This little patch however is all we need to continue now. I may come back later for more.

**Comment by hlkline** [comment]
Ok, sounds good. I'll go ahead and close this since it is being replaced by the other pull request. 
Since you mention formatting, [here](https://github.com/su2code/SU2/wiki/Style-Guide) is our style guide for reference. I think you are probably right that there are places where it is not strictly followed, and if you would like to spend the time to fix those things that would be welcome.
 
Thanks again for the pull request.

**Pull request closed without merging**
