### PR TITLE
Add regressions for all convective numerical schemes for NEMO

### PR DESCRIPTION
**Pull request by WallyMaier**
I am adding regressions for all the convective numerical schemes in NEMO using the implicit solver.  All cases run on an inviscid wedge at the moment, but I am happy to make a new folder in the regression.  

## Related Work
This will allow us to better track our changes and is the start of a more comprehensive set of regression tests for the Nemo solver coming in the future (boundary conditions, etc.) 
This directly relates to #1773 to eventually refactor the AUSM schemes.

## PR Checklist
- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with --warnlevel=3 when using meson).
- [x] My contribution is commented and consistent with SU2 style (https://su2code.github.io/docs_v7/Style-Guide/).
- [x] I have added a test case that demonstrates my contribution, if necessary.
- [] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp), if necessary.

### CODE REVIEW

**Comment by WallyMaier** [comment]
As mentioned, these all use the same geometry, and I happy to discuss inclusion of different test cases.

Also, I noticed that mutation++ does have a regression case, do we not compile M++ for regression builds?

**Review by jtneedels — COMMENTED** [review]
This looks good to me, definitely important to get test coverage on these schemes! 

Sounds like all these tested cases run, do you have a comparison of convergence history? I'd be curious if they have similar performance on this test case, and would be good to confirm correct behavior past 10 iters.

**Comment by WallyMaier** [comment]
I do not have a good grasp on the performance of each scheme.  I fear that may be a much time-intensive task, particularly since these all are implicit at the moment.

**Comment by jtneedels** [comment]
> I do not have a good grasp on the performance of each scheme. I fear that may be a much time-intensive task, particularly since these all are implicit at the moment.

I'm thinking just run this test case out to convergence for each scheme then comparing convergence histories. That way if any don't converge, we know we're not grandfathering in broken cases/schemes.

**Review by pcarruscag — APPROVED** [review]

**Review by jtneedels — APPROVED** [review]

**Comment by WallyMaier** [comment]
Here is a quick summary for the inviscid wedge case using different NEMO schemes.  There is clearly work to be done in the convergence/robustness world.
[nemo_scheme_regressions.pdf](https://github.com/su2code/SU2/files/10441554/nemo_scheme_regressions.pdf)

**Pull request merged**
