### PR TITLE
Fixes slow file I/O in Network File Systems

### PR DESCRIPTION
**Pull request by harichandiisc**
Output file writing was taking long time in NFS based cluster for huge grids (40 millions case). This change fixes this issue. 

End of line output is changed to **\n** from **endl**. **endl** forces a flush to the stream and hence incurs a performance penalty.

For a small case with 13000 points, backup time _reduced_ from 7 seconds to 0.5 seconds after this fix.

### CODE REVIEW

**Comment by hlkline** [comment]
Thanks for the contribution, that sounds like it might be a useful change if it improves performance.
Do you have any benchmarks for large cases (where frequent flushes may cause a larger performance penalty), or for cases on a non-NFS cluster? Aka, how long it took to write the large file you mention with or without this change?

I've seen some forum posts recommending using mostly "\n" for performance, with occasional "endl" to keep that buffer from being to large. It is recommended not to use endl too much with file i/o: 
http://demin.ws/blog/english/2012/04/25/endl-vs-new-line/

However, it looks like that file didn't have an endl at the end - so perhaps if you have the time you could test the performance change if you change just the last "\n" to "endl"?

**Comment by harichandiisc** [comment]
Thanks for your comments.

For a 27 million case ran on 72 cores, the backup time without modification was 1828 seconds (approx 30 minutes). After this fix, the backup time reduced to 366 seconds (approx 6 minutes). The file size was around 4.3 GB.

In my opinion, occasional "endl" is not required, since the file is closed after the writes. A file close will any way force all the writes to be flushed. 

Please give your thoughts on this.

**Comment by economon** [comment]
Thanks for bringing up this issue. It is interesting... 

As Heather mentioned, is there any concern that when writing large files the lack of an endl will cause the buffer to become too large at some point (before the file gets closed and clears the stream automatically)?

Unfortunately, we do not have any regression tests that cover the output files at the moment, so it is difficult to gauge the impact of the changes, although it would be straightforward to add some tests for SU2_CFD and SU2_SOL that diff output files. Have you been able to verify that all CSV, Tecplot/ParaView files, and force breakdown files work appropriately?

**Comment by harichandiisc** [comment]
Thanks for your comments.

Please refer http://stackoverflow.com/questions/14105650/how-does-stdflush-work

The output buffer is flushed automatically when it is full. Buffer size is usually fixed and does not depend on the count of writes. By using buffered I/O you are grouping your writes to a single step (equal to size of buffer) rather than multiple small writes (which is inefficient). 
By using "endl", we are forcing buffer flush after every line which defeats the purpose of buffered I/O.

For the paraview output files, number of new lines is very less.  So I have not made the modifications there. I have modified only output_structure.cpp, where the impact is real. The fix really helps writing of restart_flow.dat which has huge number of new lines (one for every vertex).

I have checked the output files and there is no difference after the fix.

**Comment by economon** [comment]
I've run several tests now and the output looks ok to me as well. Thanks again for the contribution. Merging this in now...

**Pull request merged**
