### PR TITLE
Remove legacy build system

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
Remove the legacy build files as mentioned in the plan for SU2 v8 #1925

### CODE REVIEW

**Review by pcarruscag — COMMENTED** [review]
The 145k lines is because we had a .vtk file committed somewhere in the repo :shrug:

**Comment by bigfooted** [comment]
It's just removing a bunch of files? Then LGTM

**Review by bigfooted — APPROVED** [review]
Nice cleanup!

**Review by WallyMaier — APPROVED** [review]
🔥

**Review by jtneedels — APPROVED** [review]
LGTM!

**Pull request merged**
