### PR TITLE
Feature custom mpi command

### PR DESCRIPTION
**Pull request by hlkline**
With this (very small) change, users can quickly change the system command used by the python scripts to launch parallel jobs without making any modifications to the code.
Example (for bash shell):
export SU2_MPI_COMMAND="mpiexec -n %i %s"

NOTE:
SU2_MPI_COMMAND must contain '%i' and '%s', in that order, which will be replaced with the number of processors and the SU2 command (ie, 'SU2_CFD config.cfg') respectively.
If this environment variable exists in the workspace, whatever is in it will be used instead of the default options. This should allow things like nonstandard mpi launchers, additional arguments like hostfiles, etc.

### CODE REVIEW

**Comment by hlkline** [comment]
Only one regtest fails - it's a slight difference from the reference value on one test, if no one objects I'll update the TestCases repo with updated reference values. (Holding off on that for now so that I don't break others' regtests in the mean time)

**Comment by LaSerpe** [comment]
Hi Heather, do you have any idea about why that regtest is failing? On travis I have the same failure on a different branch and I see that more people (#743 from Edwin's branch) had that failure too, so it doesn't depend on your modifications.

**Comment by hlkline** [comment]
I've been told that it might be a python-related thing that Tom is looking into. 
For the short term I could make a modification to that test case so that the offending value is left out entirely so that everyone's tests can pass - obviously that doesn't solve the underlying problem but it would let the other branches merge in while we figure out what's going on.

**Comment by LaSerpe** [comment]
Just approved, thanks for taking care of this!

**Pull request merged**
