### PR TITLE
Quote executable invocations on Windows to make them run.

### PR DESCRIPTION
**Pull request by ArneBachmann**

### CODE REVIEW

**Comment by hlkline** [comment]
Thanks; since the automatic tests are linux, could someone using windows please check this out and independently check its operation, just to make sure nothing unexpected happens?

**Comment by fpalacios** [comment]
Hi @ArneBachmann,

This could be an important change. Could you please provide more information about the reasons for the change and the implications?

Thanks a lot for using and developing SU2,

Best,
Francisco

**Comment by ArneBachmann** [comment]
This is simply the way how the cmd.exe shell works on Windows - file and folder names containing spaces or special characters must be quoted into `"` to be handled correctly.
The title says it all - *to make them run*.

**Comment by ArneBachmann** [comment]
I'm not a user myself, just supporting our engineers. To test Windows, however, you may look into AppVeyor, an automated testing service run on Windows free of charge for open source software.

**Comment by fpalacios** [comment]
Thanks a lot Arne,

We will accept the implementation as soon as it pass the regression tests. 

And, thanks for the AppVeyor suggestion, we´ll take a look at the software.
If you see any other problem under windows, please do not hesitate to contact us.

Best,
Francisco

**Comment by vdweide** [comment]
I am not sure whether this is the correct place to mention this, but when I build a parallel Windows version, I have to change a few things in order to make things work. I use the MinGW using the instructions given in http://www.math.ucla.edu/~wotaoyin/windows_coding.html

The changes in METIS and ParMETIS are minor and can be handled via  an #ifdef. Not sure about the mkdir command in geometry_structure.cpp though, which I just commented in order to make it work. Below are what I had to change in the develop version.

git diff Common/src/geometry_structure.cpp
diff --git a/Common/src/geometry_structure.cpp b/Common/src/geometry_structure.cpp
index 80eb3a272..fa0b7d144 100644
--- a/Common/src/geometry_structure.cpp
+++ b/Common/src/geometry_structure.cpp
@@ -11060,11 +11060,6 @@ void CPhysicalGeometry::SetTurboVertex(CConfig *config, unsigned short val_iZone
       std::string sPath = "TURBOMACHINERY";
       mode_t nMode = 0733; // UNIX style permissions
       int nError = 0;
-#if defined(_WIN32)
-      nError = _mkdir(sPath.c_str()); // can be used on Windows
-#else
-      nError = mkdir(sPath.c_str(),nMode); // can be used on non-Windows
-#endif
       if (nError != 0) {
         cout << "TURBOMACHINERY folder creation failed." <<endl;
       }

git diff externals/metis/GKlib/gk_arch.h
diff --git a/externals/metis/GKlib/gk_arch.h b/externals/metis/GKlib/gk_arch.h
index 6735c4d7c..611b7dc87 100644
--- a/externals/metis/GKlib/gk_arch.h
+++ b/externals/metis/GKlib/gk_arch.h
@@ -41,7 +41,7 @@
 #endif
   #include <inttypes.h>
   #include <sys/types.h>
-  #include <sys/resource.h>
+//#include <sys/resource.h>
   #include <sys/time.h>
 #endif

git diff externals/metis/GKlib/gk_getopt.h
diff --git a/externals/metis/GKlib/gk_getopt.h b/externals/metis/GKlib/gk_getopt.h
index 4bb86115f..597c0802a 100644
--- a/externals/metis/GKlib/gk_getopt.h
+++ b/externals/metis/GKlib/gk_getopt.h
@@ -52,11 +52,11 @@ struct gk_option {


 /* Function prototypes */
-extern int gk_getopt(int __argc, char **__argv, char *__shortopts);
-extern int gk_getopt_long(int __argc, char **__argv, char *__shortopts,
-              struct gk_option *__longopts, int *__longind);
-extern int gk_getopt_long_only (int __argc, char **__argv,
-              char *__shortopts, struct gk_option *__longopts, int *__longind);
+extern int gk_getopt(int argc, char **argv, char *shortopts);
+extern int gk_getopt_long(int argc, char **argv, char *shortopts,
+              struct gk_option *longopts, int *longind);
+extern int gk_getopt_long_only (int argc, char **argv,
+              char *shortopts, struct gk_option *longopts, int *longind);

git diff externals/parmetis/include/parmetis.h
diff --git a/externals/parmetis/include/parmetis.h b/externals/parmetis/include/parmetis.h
index b8b87cd73..c0632f8fb 100644
--- a/externals/parmetis/include/parmetis.h
+++ b/externals/parmetis/include/parmetis.h
@@ -18,7 +18,7 @@
 #include <metis.h>

 #ifndef _MSC_VER
-#define __cdecl
+//#define __cdecl
 #endif

**Comment by fpalacios** [comment]
Hi Edwin,

This a very valuable information. We need to update SU2 

Arne, are you interested in implementing and testing these changes in your pull request?

Otherwise, we can create a new pull request.

Thanks!
Francisco

**Pull request merged**
