### PR TITLE
Included Dockerfiles for multiple platforms and created a Configuration generation UI

### PR DESCRIPTION
**Pull request by skprasadu**
Hello team,

I have done following changes,
- I have created Dockerfiles for Ubuntu and CentOS and included a Readme file for people to understand how to create and setup binaries to be used, based on this pull request [#169](https://github.com/su2code/SU2/pull/169) as per Heather's recommendation
- I also created a configuration file generator to aid people to quickly create a .cfg file and use them. It is a simple HTML page without anything to be installed. For more details, please read the README.md file checked in @ SU2_IDE/Configuration-gen location.

Let me know if you have any questions.

Krishna

### CODE REVIEW

**Comment by economon** [comment]
Krishna,

Thanks for your contributions. I have a couple of questions...

1. Can the dockerfiles be made more general so that a user does not need to manually change the paths, i.e., avoid having the pathname on your machine hard-coded?

2. The config generator is nice (it seems to even be working in Safari), but I have one concern: can it be made to automatically track the current available options in the code since these change somewhat frequently? For instance, we have a gui utility that does this in Python by parsing the config_structure.cpp file for current options (SU2_PY/config_gui.py). Can your web-based tool be made to do something similar?

Tom

**Comment by skprasadu** [comment]
Thomas, I would love to address both of this. Give me some time.

I feel even in the current form, it is good. Do you have plans to merge this into master, so that people can use this to setup dev environment quickly. And also create the config file quickly. 

I will consider both of your ideas to make the user experience better.

Thanks for your support. 
Krishna

**Comment by skprasadu** [comment]
Thomas, I noticed that in under SU2_PY you have a parse_config.py that takes the cpp and hpp files and parses the data and returns it to the python UI. What is the data structure for this, is this like a data dictionary, key, value pair? can you give me the data structure for this so that I can reuse this in the web app. Thanks for your help.

Krishna

**Comment by skprasadu** [comment]
Never mind, I understood how parse_config.py is parsing.. let me get back to you.

Krishna

**Comment by skprasadu** [comment]
Tom,

I have completed the basic html 5/ javascript based configuration generator. Please to thru the readme.md of SU2_IDE/Configuration-gen folder in develop branch and follow the instruction.

Thanks
Krishna

**Comment by oleburghardt** [comment]
Dear @skprasadu 
As this PR is open now for a very long time and possibly outdated, I will close it for now. We emphasize that you are very welcome to open a new one anytime.

**Pull request closed without merging**
