### PR TITLE
Added low-Mach number correction of Thornber et al.

### PR DESCRIPTION
**Pull request by daniel-linton**
Added low-Mach number correction of Thornber et al.* to Upwind_Residual along with flag for activating the option (LOW_MACH_CORR=TRUE|FALSE).

*Thornber, B., Mosedale, A., Drikakis, D., Youngs, D., Williams, R.J.R.,
"An improved reconstruction method for compressible flows with low Mach
number features", Journal of Computational Physics, Jan 2008, Vol. 227,
No. 10, pp. 4873-4894.

### CODE REVIEW

**Comment by hlkline** [comment]
looks good to me, except that there are conflicts. Please fix the conflict - see command line instructions provided by github - and push the change into your branch. When your branch is updated the pull request will be automatically updated and the regression test will be run.

**Comment by daniel-linton** [comment]
Thanks for that Helen. I hope I've done it correctly, I had a bit of trouble getting it merged together.

**Comment by economon** [comment]
Hi Daniel! Thanks again to you and Ben for working on this new feature... it is going to be a nice contribution to the code.

The code looks good to me, but there is an issue with the automatic differentiation build. It is an easy fix though: please change your "double" declarations to "su2double" in the commits. We use "su2double" everywhere in the code so that it is straightforward to specialize the variable types at compile time, which is needed by the AD tool. Once the tests pass, we'll pull this in right away.

**Comment by daniel-linton** [comment]
Hi Tom, thanks for that, I was a bit confused as it compiled on my system. I've fixed the double declarations so hopefully it's all good now.

**Comment by economon** [comment]
Thanks for fixing up those conflicts, Daniel. I'm merging this in now, and I'll be in touch directly about getting a test case set up for the new low-Mach correction.

**Pull request merged**
