### PR TITLE
Feature general hllc

### PR DESCRIPTION
**Pull request by LaSerpe**
In this branch the HLLC algorithm has been generalized to Non-Ideal flows so that now it can be used with more complex equations of state. Computation on nicfd LS89 test case with Van der Waals eos show quite similar Cd/Cl predicted values.

Furthermore I cleaned up a little bit the original CUpwHLLC_Flow::ComputeResidual: there were some redundancies (some variables were computed twice). I also made changes that in my opinion improve code readability. Regression tests (for the original HLLC) passed on my PC with a difference of 1E-6 on RhoE residual (slight differences were anyway expected).

A couple of bugs fixed.

Cheers 
Giulio

### CODE REVIEW

**Comment by economon** [comment]
Thanks for this, Giulio, it looks like a nice implementation. And thank you for taking the time to clean up the original HLLC method a bit.

It looks like you are basing the Jacobian terms on the Roe implementation (like we do in the ideal gas situation). Out of curiosity, will you be interested in having the Jacobians for the HLLC method directly?

Also, I noticed that there are some commented cout statements in the config post-processing (in the ideal gas condition check). Could you please remove those when you have a minute?

**Comment by LaSerpe** [comment]
ok I just removed the commented lines!
Sorry about that, I initially put there those "couts" cause I first thought about throwing out a warning string (in case users try to impose Gamma and Gas_constant using standard_air model) and then I forgot to remove them. 
This is a bug from the current develop branch actually: right now it is possible to change gamma even though one chooses the std_air model.
It happened to me that simulations were not converging and giving weird behaviour just because I forgot to remove the option from the config file. I put that correction but maybe you've a better idea on how to handle this?

Regarding the Jacobians, you're right, right now the implementation is exactly the generalization of the one implemented in the original ideal gas situation (Roe). Maybe in the future we will work also on Jacobians for the HLLC but that's something I don't really need them right now. I can talk with folks here in Milano or in Delft and see if there a critical mass calling for that implementation.

**Comment by economon** [comment]
Got it. Please do let me know if there is interest in the HLLC Jacobian terms.

Looks good to me otherwise. We'll merge this in...

**Comment by LaSerpe** [comment]
Hi,
lately I've been working for the implementation of the Jacobians for the HLLC method (you can have a look at feature_HLLC_jacobians branch).
Everything is working fine for real gas though I'm still working to add moving grid features.

By the way would be interesting for anybody to have the same implementation also for ideal gases?
In case I can modify also the former version which uses Roe Jacobians..

**Comment by economon** [comment]
Giulio,

Yes! It would be excellent to have the HLLC Jacobians for the ideal gas case too. Please let me know if I can assist with anything. You might also have noticed some old commented out code that you could use as a guideline.

Tom

**Pull request merged**
