### PR TITLE
This is a read_target_file_AD commit

### PR DESCRIPTION
**Pull request by jaspe55**
## Proposed Changes
*in driver_structure.cpp, a few lines have been included to force reading the Target files when running discrete adjoint. I tested it on MacOS El Capitán and OpenSUSE 42.3 with the most recent g++. Under MacOS, the MPI flavour is openmpi; on openSUSE, the MPI flavour is mpich2psm2*
 

## Related Work
This fix forces the reading of Target Files in an inverse design project when using discrete adjoint.

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [ X] I am submitting my contribution to the develop branch.
- [X ] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [X ] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by economon** [comment]
Hi @jaspe55 - thanks for the first contribution!

Can you please switch the email and branch name in .travis.yml back to su2code-dev@lists.stanford.edu and develop, respectively? That should get the tests running so we can give this a proper review (should be quick given the small change).

**Comment by jaspe55** [comment]
Dear sirs, I just modified .travis.yml back to
su2code-dev@lists.stanford.edu and develop respectively:

Jairos-Mac-mini:SU2 jaspe$ git status

On branch feature_force_read_target_on_AD

Changes not staged for commit:

  (use "git add <file>..." to update what will be committed)

  (use "git checkout -- <file>..." to discard changes in working directory)


modified:   .travis.yml


no changes added to commit (use "git add" and/or "git commit -a")

Jairos-Mac-mini:SU2 jaspe$ git commit -am "This is an update of .travis.yml
for feature_force_read_target_on_AD."

[feature_force_read_target_on_AD 3f2115373] This is an update of
.travis.yml for feature_force_read_target_on_AD.

 1 file changed, 2 insertions(+), 2 deletions(-)
After that, I issued git push origin feature_force_read_target_on_AD, and
got the error message:

To https://github.com/su2code/SU2.git

 ! [rejected]            feature_force_read_target_on_AD ->
feature_force_read_target_on_AD (fetch first)

error: failed to push some refs to 'https://github.com/su2code/SU2.git'

hint: Updates were rejected because the remote contains work that you do

hint: not have locally. This is usually caused by another repository pushing

hint: to the same ref. You may want to first integrate the remote changes

hint: (e.g., 'git pull ...') before pushing again.

hint: See the 'Note about fast-forwards' in 'git push --help' for details.
I issued then git pull origin develop, to merge changes in remote to my
local branch, successfully , but a new git push origin
feature_force_read_target_on_AD, produced the same error message.
Would be the first commit command enough?

    With kind regards,

         Jairo

**Comment by economon** [comment]
No problem at all. I think the issue was that others had merged the changes into develop here from the web interface and those changes needed to be pulled down into your local copy before you could push the changes to .travis.yml up.

I have just made the change, and I see the tests are now running! We'll get back with a review soon.

**Comment by economon** [comment]
@jaspe55 : looks like there is a compile error due to the CSolver input to the modified functions (I think one index is missing, probably '[iInst]'. Can you please take a look when you get the chance?

**Comment by jaspe55** [comment]
Dear Dr Economon and fellows,

Thank you for the remarks.
I have included reference to index INST_0 to the code in the local branch,
and compiled it in a MacOS (El Capitán):
Successfull compilation for Inverse Design Cp  & Inverse Design HeatFlux.
External METIS lib caused eight warnings on arguments of abs() function:
Suggestion is to use *llabs*() instead of *abs*(). Please see appended
extract.
I am running a local test now, which uses Inverse Design Cp; and as soon as
it finishes, I will update the remote too, so we can continue the tests.

 With kind regards,

     Jairo

  CC       libmetis/libmetis_a-mincover.o

*../../../externals/metis/libmetis/parmetis.c:311:15: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^*

*../../../externals/metis/libmetis/parmetis.c:311:15: **note: *use function
'llabs'

      instead

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^~~*

              llabs

*../../../externals/metis/libmetis/parmetis.c:336:17: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[from]-rinfo[higain]....

*                ^*

*../../../externals/metis/libmetis/parmetis.c:336:17: **note: *use function
'llabs'

      instead

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[from]-rinfo[higain]....

*                ^~~*

                llabs

*../../../externals/metis/libmetis/parmetis.c:540:15: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^*

*../../../externals/metis/libmetis/parmetis.c:540:15: **note: *use function
'llabs'

      instead

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^~~*

              llabs

*../../../externals/metis/libmetis/parmetis.c:583:17: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[other]-rinfo[higain]...

*                ^*

*../../../externals/metis/libmetis/parmetis.c:583:17: **note: *use function
'llabs'

      instead

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[other]-rinfo[higain]...

*                ^~~*

                llabs

  CC       libmetis/libmetis_a-mmd.o

  CC       libmetis/libmetis_a-pmetis.o

4 warnings generated.

  CC       libmetis/libmetis_a-ometis.o

  CC       libmetis/libmetis_a-refine.o

  CC       libmetis/libmetis_a-separator.o

  CC       libmetis/libmetis_a-options.o

  CC       libmetis/libmetis_a-parmetis.o

  CC       libmetis/libmetis_a-sfm.o

*../../../externals/metis/libmetis/parmetis.c:311:15: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^*

*../../../externals/metis/libmetis/parmetis.c:311:15: **note: *use function
'llabs'

      instead

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^~~*

              llabs

*../../../externals/metis/libmetis/parmetis.c:336:17: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[from]-rinfo[higain]....

*                ^*

*../../../externals/metis/libmetis/parmetis.c:336:17: **note: *use function
'llabs'

      instead

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[from]-rinfo[higain]....

*                ^~~*

                llabs

*../../../externals/metis/libmetis/parmetis.c:540:15: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^*

*../../../externals/metis/libmetis/parmetis.c:540:15: **note: *use function
'llabs'

      instead

    mindiff = abs(pwgts[0]-pwgts[1]);

*              ^~~*

              llabs

*../../../externals/metis/libmetis/parmetis.c:583:17: **warning: **absolute
value*

*      function 'abs' given an argument of type 'long long' but has
parameter of*

*      type 'int' which may cause truncation of value [-Wabsolute-value]*

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[other]-rinfo[higain]...

*                ^*

*../../../externals/metis/libmetis/parmetis.c:583:17: **note: *use function
'llabs'

      instead

      newdiff = abs(pwgts[to]+vwgt[higain] - (pwgts[other]-rinfo[higain]...

*                ^~~*

                llabs

  CC       libmetis/libmetis_a-srefine.o

**Comment by jaspe55** [comment]
Hello Dr. Economon,

   Thank you for your quick response.
   I just push the updates, following the suggested hints in the messages of the first "git push ..." command, but even after issued the "git pull ...", I still received the same message (please find the dialog appended at the end of this note). 

      With kind regards,

        Jairo (jaspe55)
.........................................................................................................................................................
Jairos-Mac-mini:SU2 jaspe$ pwd
/Users/jaspe/Desktop/SU2BRANCH/SU2
Jairos-Mac-mini:SU2 jaspe$ git branch
* feature_force_read_target_on_AD
  master
Jairos-Mac-mini:SU2 jaspe$ git status
On branch feature_force_read_target_on_AD
nothing to commit, working tree clean
Jairos-Mac-mini:SU2 jaspe$ 
Jairos-Mac-mini:SU2 jaspe$ 
Jairos-Mac-mini:SU2 jaspe$ git push origin feature_force_read_target_on_AD
To https://github.com/su2code/SU2.git
 ! [rejected]            feature_force_read_target_on_AD -> feature_force_read_target_on_AD (fetch first)
error: failed to push some refs to 'https://github.com/su2code/SU2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Jairos-Mac-mini:SU2 jaspe$ git pull origin develop
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 81 (delta 45), reused 46 (delta 44), pack-reused 31
Unpacking objects: 100% (81/81), done.
From https://github.com/su2code/SU2
 * branch                develop    -> FETCH_HEAD
   0811066f4..cf91b7cf4  develop    -> origin/develop
Merge made by the 'recursive' strategy.
 Common/include/blas_structure.hpp               |   2 +-
 Common/include/matrix_structure.hpp             |   2 +-
 Common/src/adt_structure.cpp                    |  11 +-
 Common/src/blas_structure.cpp                   |  27 ++--
 Common/src/fem_geometry_structure.cpp           |   2 +-
 Common/src/geometry_structure.cpp               | 131 ++++++++++++++-----
 Common/src/matrix_structure.cpp                 |  14 +-
 Common/src/wall_model.cpp                       |   4 +-
 SU2_CFD/src/output_structure.cpp                |   2 +-
 SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj | 166 ++++++++++++------------
 SU2_IDE/Xcode/SU2_DEF.xcodeproj/project.pbxproj | 144 ++++++++++++++++----
 SU2_IDE/Xcode/SU2_DOT.xcodeproj/project.pbxproj | 130 +++++++++++--------
 SU2_IDE/Xcode/SU2_GEO.xcodeproj/project.pbxproj |  74 ++++++++++-
 SU2_IDE/Xcode/SU2_MSH.xcodeproj/project.pbxproj | 124 ++++++++++++++++--
 SU2_IDE/Xcode/SU2_SOL.xcodeproj/project.pbxproj |  62 +++++----
 TestCases/parallel_regression.py                |  26 ++--
 TestCases/parallel_regression_AD.py             |   4 +-
 TestCases/serial_regression.py                  |  24 ++--
 TestCases/serial_regression_AD.py               |   2 +-
 19 files changed, 659 insertions(+), 292 deletions(-)
Jairos-Mac-mini:SU2 jaspe$ git push origin feature_force_read_target_on_AD
To https://github.com/su2code/SU2.git
 ! [rejected]            feature_force_read_target_on_AD -> feature_force_read_target_on_AD (fetch first)
error: failed to push some refs to 'https://github.com/su2code/SU2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Jairos-Mac-mini:SU2 jaspe$

**Comment by economon** [comment]
Thanks, @jaspe55 ! LGTM. I don't think we have any tests for the inverse design capability. Do you have a very simple test case that we can put into the regressions for this capability? I think you are working on a nozzle design.

**Comment by talbring** [comment]
Hi Jairo, 

what is the status here ? Is it possible to provide a simpler (smaller) case ?

**Comment by jaspe55** [comment]
Hello Dr. Albring,

 Yes! Sorry for the delay due some internal presentations and events here.
 I just finished a small model and successfully tested it on openSUSE. I expect to upload it today.

   With kind regards,

        Jairo

**Comment by jaspe55** [comment]
Dear Dr. Economon,

 Thank you again for your guidance.
 The git add, git commit and git push commands worked as expected.
 The only problem I had was when I tried to upload the mesh file to https://github.com/su2code/TestCases/tree/develop/disc_adj_euler: <https://github.com/su2code/TestCases/tree/develop/disc_adj_euler:> I wanted to upload a folder “arina2k”, whose contents is the mesh file (.su2). I could not just upload the folder name: the system appears to be waiting for an actual file name. When I choose the file name inside that folder , it appears that the system would upload the file within the  repository, but 'discarding’ its folder name, so I would have an ‘orphaned’ file there. I tried also to create a file (which would be my folder name), but again, I am prompted with an editor in order to write an actual file, using directly the browser. I believe that there is a simple way to upload a sub-directory/filename, but i could not realize it.

   With kind regards,

      Jairo

**Comment by economon** [comment]
I have just uploaded an empty file as a placeholder for your mesh, @jaspe55. Can you please try to update your local copy of the develop branch from the TestCases repository and then overwrite the empty file with your mesh? You can find the file in TestCases/disc_adj_euler/arina2k/, or view in the browser here:

https://github.com/su2code/TestCases/tree/develop/disc_adj_euler/arina2k

**Comment by jaspe55** [comment]
Dear Dr. Economon,

 I have uploaded a non-empty file (Arina2Kmesh.su2) to the develop branch and I was able to see the updated file in https://github.com/su2code/TestCases/tree/develop/disc_adj_euler/arina2k <https://github.com/su2code/TestCases/tree/develop/disc_adj_euler/arina2k>
Please find a glance of the evidence in the file appended to this note.
I realised that the uploading was effective after I committed it.
 So I believe that now things are in the proper places.

   With kind regards,

      Jairo

**Comment by economon** [comment]
@jaspe55 : I have just cleaned up a couple of things and can confirm that your mesh file is there. However, we are missing the converged solution file (solution_flow.dat) and the target Cp file for inverse design.

Similar to the process for the mesh, can you please upload the solution file to the TestCases repo and the target Cp file to the SU2 code repo (alongside the config file)? Once the files are present, we can update the regression values in the serial_regression_AD.py and parallel_regression_AD.py files, and this PR will be ready to merge.

**Comment by jaspe55** [comment]
Dear Dr. Economon, 

  I just uploaded the mentioned files. I hope everything may be ok now.

   With kind regards,

     Jairo

**Comment by jaspe55** [comment]
Ok. I will do it  as soon as possible. 

  With kind regards,

      Jairo

**Comment by jaspe55** [comment]
Dear Dr. Economon,

  I just finished the run on AD with the files you have adjusted and it did
converge. I also have successfully run some simple inverse design tests
with a limit on the number of cycles.
  Thank you very much for your guidance and help.

      With kind regards,

              Jairo

**Comment by economon** [comment]
Wonderful! Time to merge this one

**Comment by jaspe55** [comment]
Thank you, Dr. Economon.
When you say "Time to merge this one": Is this an action I should take, or
is it accomplished in the SU2 standard schedule ?

    With kind regards,

             Jairo

**Comment by economon** [comment]
Was just waiting for the tests to finish. Merging now. Thanks again for the effort

**Comment by jaspe55** [comment]
Ah! Ok!

 Thank you, again.

   Kind regards,

      Jairo

**Pull request merged**
