### PR TITLE
Cleaning up compiler warnings

### PR DESCRIPTION
**Pull request by hlkline**
There were several places where the compiler was returning warnings, for things like comparing signed and unsigned integers, uninitialized variables, unused variables, etc. 
This pull request corrects for these warnings; the largest change is in changing the type of some consts that previously returned signed-unsigned comparison warnings.

### CODE REVIEW

**Comment by economon** [comment]
Good idea. I am going to pull this down too and check warnings on Mac as well. I'll add anything to this PR.

**Comment by hlkline** [comment]
Thanks for reminding me - I am going to switch that now; if my next push passes the tests (in a few minutes, after I test it on my system) I'm fine with merging after that.

**Comment by hlkline** [comment]
Done with updates; ready to merge.

**Comment by economon** [comment]
Great. Thanks, Heather!

**Pull request merged**
