### PR TITLE
Feature mrf

### PR DESCRIPTION
**Pull request by salvovitale**
Hey guys,

the code now works for multizone periodic meshes. After the FSI meeting of yesterday i had a small chat with Ruben and it showed me what was most likely the problem in the geometry_structure.cpp preventing the run of a multizone periodic mesh. I slightly modified the loop, actually now there are 2 loops one reading the marker and another reading the periodic transformations and it works.
     
Thomas  your implementation of the multi rotating frame is also working, so now is possible to specify different rotational speeds for each mesh. I attached a picture of a simulation with 2 meshes one with rotational speed and one without. The simulation of the picture doesn´t  have any particular meaning, it  was just to check if two periodic mesh with 2 different rotational speed can be simultaneously run by SU2. 

cheers!!!
 
2periodicmesh_multirotating

### CODE REVIEW

**Comment by juanjosealonso** [comment]
Nice job Salvo!

Cheers,

Juan

On Jul 30, 2015, at 7:02 AM, Salvatore Vitale <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey guys,

the code now works for multizone periodic meshes. After the FSI meeting of yesterday i had a small chat with Ruben and it showed me what was most likely the problem in the geometry_structure.cpp preventing the run of a multizone periodic mesh. I slightly modified the loop, actually now there are 2 loops one reading the marker and another reading the periodic transformations and it works.

Thomas your implementation of the multi rotating frame is also working, so now is possible to specify different rotational speeds for each mesh. I attached a picture of a simulation with 2 meshes one with rotational speed and one without. The simulation of the picture doesn´t have any particular meaning, it was just to check if two periodic mesh with 2 different rotational speed can be simultaneously run by SU2.

cheers!!!

[2periodicmesh_multirotating]<https://cloud.githubusercontent.com/assets/6718364/8984481/2f80c900-36d2-11e5-973d-f72adc9a476a.jpg>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/su2code/SU2/pull/186

Commit Summary

  *   Modified grid movement options and set up to allow multiple rotating frames with multi-zone calculations.
  *   fix problem reading multizone mesh periodic

File Changes

  *   M Common/include/geometry_structure.hpp<https://github.com/su2code/SU2/pull/186/files#diff-0> (9)
  *   M Common/include/geometry_structure.inl<https://github.com/su2code/SU2/pull/186/files#diff-1> (2)
  *   M Common/src/config_structure.cpp<https://github.com/su2code/SU2/pull/186/files#diff-2> (5)
  *   M Common/src/geometry_structure.cpp<https://github.com/su2code/SU2/pull/186/files#diff-3> (38)
  *   M SU2_CFD/src/iteration_structure.cpp<https://github.com/su2code/SU2/pull/186/files#diff-4> (8)

Patch Links:

  *   https://github.com/su2code/SU2/pull/186.patch
  *   https://github.com/su2code/SU2/pull/186.diff

**Comment by economon** [comment]
Salvo,

This is great, but it looks like there are some conflicts here.. can you please merge the develop branch back into the feature_mrf branch locally in your copy to see what is wrong? You can add additional commits here to this pull request until we get it fixed.

Tom

**Comment by salvovitale** [comment]
yep sure!!!

**Comment by salvovitale** [comment]
Hey Thomas,
I merged with the develop branch. Now there are not conflicts. But in the parallel regression test the first testcase the contadj_oneram6 failed. Do you think that it´s something related with the feature_MRF?


cheers!!

**Comment by economon** [comment]
No, I think we're all set. I am going to merge this in. We have two issues that we are going to be clearing up very soon: the ONERA M6 adjoint case that is failing somewhat irregularly, and a reorganization of the test cases/config files to make the regression tests more effective (in particular for pull requests). Thanks for fixing the conflicts!

**Pull request merged**
