### PR TITLE
Update of meson and ninja to most recent version

### PR DESCRIPTION
**Pull request by talbring**
## Proposed Changes

This updates ninja and meson submodules. 

## Related Work

Should solve e.g. the problem of finding python 3.8 mentioned in #991 

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [x] My contribution is commented and consistent with SU2 style.
- [x] I have added a test case that demonstrates my contribution, if necessary.
- [x] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by talbring** [comment]
Also updated the AUTHORS.md file. We had some new contributors.

**Comment by GomerOfDoom** [comment]
Hi @talbring ,

In order to fix the build process for Python 3.8, I believe we still need to add in the changes to the `meson.build` files I made in branch `fix_python_3.8`. Do you want to merge that into this branch before merging the PR, or should we do separate PRs?

-Paul

**Comment by talbring** [comment]
@GomerOfDoom I just manually copied it over (with a small change). I hope that is ok! Thanks for the fix!

**Comment by GomerOfDoom** [comment]
Looks good to me! I just tested your branch on my system and it works. I'll delete my branch. While we're here, are there additional changes that need to be made for openblas (along the lines of what are mentioned in issue #991), or is that an ArchLinux issue, only?

**Comment by pcarruscag** [comment]
No changes to blas

**Pull request merged**
