### PR TITLE
SU2_PY: Fix multiple TabError and SyntaxError in python scripts

### PR DESCRIPTION
**Pull request by band-a-prend**
This patch fix multile errors while python byte-compilling:

- TabError: inconsistent use of tabs and spaces in indentation;
- SyntaxError: invalid syntax (for 'raise' and 'print' functions).

## Proposed Changes
In some Linux distributive, e.g. Gentoo, before installation phase the python byte compile action is required for python scripts being installed. Such scripts are under `SU2/SU2_PY` directory.

During **python3** byte compilation of mentioned scripts multiple TabError and SyntaxError take place.
To reproduce this errors go to the `SU2/SU2_PY` source directory and run `python -m compileall .` command. The following error messages appears:
```
Listing '.'...
Listing './FSI'...
Compiling './FSI/FSIInterface.py'...
*** Sorry: TabError: inconsistent use of tabs and spaces in indentation (FSIInterface.py, line 50)
Compiling './FSI/PitchPlungeAirfoilStructuralTester.py'...
*** Sorry: TabError: inconsistent use of tabs and spaces in indentation (PitchPlungeAirfoilStructuralTester.py, line 177)
Listing './FSI/io'...
Compiling './FSI/io/FSI_config.py'...
*** Sorry: TabError: inconsistent use of tabs and spaces in indentation (FSI_config.py, line 61)
Listing './FSI/util'...
Listing './SU2'...
Listing './SU2/eval'...
Listing './SU2/io'...
Listing './SU2/mesh'...
Listing './SU2/opt'...
Listing './SU2/run'...
Listing './SU2/util'...
Compiling './SU2/util/filter_adjoint.py'...
***   File "./SU2/util/filter_adjoint.py", line 182
    raise Exception, 'unknown filter type'
                   ^
SyntaxError: invalid syntax

Compiling './compute_uncertainty.py'...
***   File "./compute_uncertainty.py", line 69
    print "\n\n =================== Performing " + str(comp) + "  Component Perturbation =================== \n\n"
                                               ^
SyntaxError: invalid syntax

Compiling './fsi_computation.py'...
*** Sorry: TabError: inconsistent use of tabs and spaces in indentation (fsi_computation.py, line 77)
Listing './pySU2'...
```
After fixing them and running `python -m compileall .` again the next set of similar error messages appears.

This patch fix such `TabError`, `SyntaxError` (for `raise` and `print` functions), replace some indent tabs with spaces (generally with 8 spaces) before comments, remove trailing spaces where needed.

Please fix this small issue as resulting patch to fix it for distributive build script is rather huge (~ 100 Kb). Many changes are in `SU2_PY/FSI/FSIInterface.py` and the `Split` mode of github change preview is more suitable to compare and to recheck the correctness of new indentation (or via Meld application).

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [ ] I am submitting my contribution to the develop branch.
- [ ] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [ ] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by band-a-prend** [comment]
Should I fix PEP8 issues or left this part of code as is?

**Comment by pcarruscag** [comment]
Welcome to SU2 and thank you for fixing these issues :+1: 

Some of the files you changed are removed in #902, please revert those changes to avoid merge conflicts.

**Comment by band-a-prend** [comment]
I removed from pull request the files removed in another pull request.

I also tried to fix some PEP8 issues including "useless `return`" in one function.
The remain CodeFactor issues:
 * `Use of eval (eval-used)` - there is check for `window` is presented in allowed value list, 
so it safe to eval this value currently.
* `Wildcard import math (wildcard-import)` - I have no idea what math expressions are used in this file. 
Maybe it could be removed. As I don't know if it will brake something in case of replacing it with `import math` instead of `from math import *`.
* `Redefining built-in 'pow' (redefined-builtin)` - is related to previous issue.

**Comment by band-a-prend** [comment]
Should I rebase commits?

**Comment by pcarruscag** [comment]
@talbring any way to bypass codefactor when the errors are not due to the changes introduced in the PR?

**Pull request merged**
