### PR TITLE
Parallel Output

### PR DESCRIPTION
**Pull request by economon**
This pull request is the first phase of an overhaul of the COutput class. As a first step, the serial bottleneck for merging and writing output data in SU2_CFD has been removed in favor of entirely parallel routines for sorting and writing output data. The routines work by sorting the output data into linear partitions on all ranks such that each processor owns an equal chunk of the output. This PR introduces these new routines along with parallel restart (ASCII) and Tecplot (ASCII) file writers. For now, there is no major change to the behavior of the code, other than potential savings in memory and time for file output with SU2_CFD, as this phase was simply a refactoring and rewrite that maintains identical output to the serial version. 

Important notes:
* While restarts are now written in parallel, they should contain the exact same information as before. Please make sure your solvers are behaving as expected.
* This refactoring finally allows for users to easily register new variables (including custom variables names) for the output files by separating the loading of local data for the different solvers from the MPI communications and the eventual writing of files. Please see the LoadLocalData_* routines in output_structure.cpp that are now defined for different solvers, which will eventually become virtual functions within child classes of COutput for different physics. 
* SU2_SOL remains intact for now and works the same as before. Parallel file writers for other formats (ParaView, CGNS) are forthcoming, and will eventually replace the remaining serial versions.
* The next step after this PR is to switch the restarts to binary with MPI-IO and to update the restart loaders in all solvers.
* This PR also fixes some memory leaks.

### CODE REVIEW

**Comment by LaSerpe** [comment]
Tom, thank you for improving this one.
This sounds cool, I was really looking for an easy way to customize the output to plot, for instance, the entropy field or the mass flow for turbomachinery applications. 
Is this meant to remain hard-coded or are you planning to introduce new options to specify the output from the config file?

I see reg tests failing due to travis time out (I believe we have 50 minutes for each python script). I also experienced that issue before and I had to turn down a couple of check I wanted to add for sliding meshes. We need to think about reorganising reg test to reduce or shorten them without loosing control on code features.
Otherwise we could consider switching to travis.com but I believe we'll have to pay for that.

looks good to me by the way. 

Ciao!
Giulio

**Comment by talbring** [comment]
Hey Tom,

this was fast ! Thanks for the first step in making the output structure more efficient and flexible. So far it looks good. I'll test it for the adjoint soon.

@LaSerpe I think for the beginning these things will be hard-coded. But defining this in the config file is definitely a feature we should discuss.

**Comment by economon** [comment]
Thanks, Giulio and Tim. I'll look into the time out issues with Travis, as I am seeing this in other branches now too.

Please let me know when you have a chance to test this. I would like to merge this and the incompressible PRs in as soon as we can.

**Comment by economon** [comment]
@talbring: thanks for sharing the failing test case for the incompressible problem. This all seems to be working for me now. Can you please take a look when you have a chance to make sure it is ok for you now too? Otherwise, I think this PR is almost ready once the tests pass.

**Comment by talbring** [comment]
Also works for me now! Thanks for fixing this.

Travis failed due to reaching the maximum time for a job. The usual time the serial test take in other PRs is like 45 min, but this one was killed after 1h 9 min. Is there something that could go wrong in the non-mpi case ?

I just restarted the tests to see whether it occurs again.

**Comment by economon** [comment]
Great. I have seen it stall sometimes, but usually a restart is fine. Btw, as I mentioned in other comments, we now have a total of 70 minutes for our tests in Travis CI. It's not a long term solution, but it will hold us over for some time.

We have a bit of a logjam with pull requests right now. We'll merge in some of the smaller ones / bug fixes first, but then I'll get this one merged in the near future.

**Pull request merged**
