### PR TITLE
Feature low mach reconstruct - regression test case

### PR DESCRIPTION
**Pull request by daniel-linton**
Added a regression test case for the low Mach number reconstruction. Uses the same mesh as the existing cylinder_lam test case.

### CODE REVIEW

**Comment by economon** [comment]
Looks good to me. Thanks for adding the test, Daniel. Merging this in now...

**Comment by LaSerpe** [comment]
Hi guys, 
sorry for re-opening this request, I have a brief question for you Daniel.
In the test case you added I see that there are some numbers that look weird to me (the free-stream pressure is 17 Pa and density is 0.00021). Since I modified the HLLC solver, which is used in this particular test case, I'm having troubles in passing this regression tests. Are those values correct? 

Cheers,
Giulio

**Comment by daniel-linton** [comment]
Hi Giulio,

Yes, those values are correct. I also get similar numbers for the other laminar cylinder test case without the low Mach correction and using the Roe solver. You're right they are weird though, it's because the fluid properties are those of air at 288.15 K so to get the low Reynolds number the density must be very low (correct me if I'm wrong!). Perhaps the fluid properties of honey would be more realistic for this case.

Regards,
Daniel

**Comment by LaSerpe** [comment]
Yeah, I also tried the Roe case which actually gives more strange numbers (1.7 Pa), but by the way these are only tutorials.

regarding the Reynolds number, that's correct, lowering density will also lower the Reynolds number. But reducing the Mach number (and thus free-stream speed) is also a way. The thing is that the HLLC solver I'm testing works pretty well for the supersonic wedge (an also for others) but suffers a lot this test case (computation explodes at first iteration). 
Can we think about changing the config file a little bit (perhaps changing the fluid)? Is there a particular reason why the HLLC solver is needed here?

**Comment by daniel-linton** [comment]
The low Mach number correction scheme was developed with the HLLC solver in mind; which is the only reason HLLC is used in the test case. The correction should work with any full, non-preconditioned Riemann solver, so the test case could use the Roe solver. However, I think there needs to be a well-defined reason for changing the test case. The HLLC solver worked for that test case when it was set up, do you know why the recent changes have caused it to fail?

**Comment by LaSerpe** [comment]
The current version of the HLLC solver (the one in the develop branch) computes the jacobians terms using Roe approach. The implementation I'm testing uses instead the direct formulation. This of course changes a lot the behaviour of the implicit scheme which now seems to be less robust, at least for this test case.
Today I made some tests and what I  propose is to modify the config file in order to run a non-dimensional simulation with a CFL = 1.0. Would that be possible?
Tomorrow I will look again for bugs in my branch.

Just another small question: I saw that in the for cycle at line 3674 of solver direct mean (of develop branch), in the part regarding the low mach number correction, vel_i_corr and vel_j_corr are declared as 3 element arrays. The code cycle over [iDim+1] for those arrays. Could this bring to a vector overflow in the 3D case?

Cheers,
Giulio

**Comment by daniel-linton** [comment]
You're right about that bug with vel_i_corr. Thanks for finding it, I'll submit a correction.

Yes, it's possible to modify the config file so that your implementation works. But is this simply masking the problem of reduced stability? Do you expect the direct formulation to be less stable? And do the benefits of the direct formulation make the loss of stability worthwhile? If so, then I think you should change the config file.

I hope this answers your question, I'm not sure if I understood it correctly.

Regards,
Daniel

**Comment by LaSerpe** [comment]
Yes, the new jacobian implementation is less diffusive. Besides this, the low Mach number correction also results in less diffusive, final, formulation (as Tornber says in his paper). I expect this to result in reduced stability when the flow has  very sharp discontinuities, like the contact surface between the recirculation zone and the external flow, since they are better captured.
I have made some modification to my implementation and now it works also for this test case (though CFL has to be lowered from 4.0 to 2.0, as I was expecting,  to make it eventually converge).
If this looks good to you, I'll change the CFL number and push it to the repo.

Regards,
Giulio

**Pull request merged**
