### PR TITLE
Update CoDiPack.

### PR DESCRIPTION
**Pull request by jblueh**
## Proposed Changes
Update SU2 to a CoDiPack version that contains the fixes discussed in #1087.
 

## Related Work
#1087

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [X] I am submitting my contribution to the develop branch.
- [ ] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [ ] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by pcarruscag** [comment]
Thank you @MaxSagebaum and @jblueh

**Review by pcarruscag — APPROVED** [review]

**Comment by TobiKattmann** [comment]
Hi @jblueh , can we update medipack as well to the latest commit? 

(As you know 😉) It solves a minor inconvenience where Macs with case-insensitive filesystems would mark the medipack submodule as unclean because two filenames just differ just in their case [see here](https://github.com/SciCompKL/MediPack/pull/3).

Building on my machine was without problems and if the regression test would run here I see no issue. I can also add the commit but didnt want to sneak into your PR without asking ;)

**Comment by jblueh** [comment]
Hi @TobiKattmann, thanks for pointing this out! I added the update.

**Review by TobiKattmann — APPROVED** [review]
Thanks 💐

**Pull request merged**
