### PR TITLE
Revert "Update of codi and medi"

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
@oleburghardt, according to @talbring this was supposed to go AFTER #653. Is my work a joke around here or what?!
 

## Related Work
*Resolve any issues (bug fix or feature request), note any related PRs, or mention interactions with the work of others, if any.*

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [ ] I am submitting my contribution to the develop branch.
- [ ] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [ ] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by oleburghardt** [comment]
> @oleburghardt, according to @talbring this was supposed to go AFTER #653. Is my work a joke around here or what?!
Sorry, haven't been aware of that. Just had a look at the code which looked good to me.

**Comment by rsanfer** [comment]
Ok, so it was a mistake, which is exactly why version control is in place. Let's keep it calm, we can fix it.

**Comment by talbring** [comment]
@pcarruscag You are absolutely right in that I said we should merge both of your PRs in first. I know that it is sometimes frustrating when it takes more time than it should, before we (or I) can do a review ...

**Comment by economon** [comment]
Yep, just an honest mistake. We'll fix it up.

I know that things have been a little quiet in the repository lately, but there is a lot of motion happening behind the scenes as we prepare for the developers meeting next month (we have some exciting things in store). 

Thanks for the patience, and I would also ask that, if folks in the community have some time, they please contribute to reviews. Expertise in the particular area is not required (I know it can seem intimidating, but don't be shy!), and it is a great way to learn the code and see what other folks are developing. The more input and discussion we have from various perspectives, the better.

**Comment by talbring** [comment]
My suggestions: Let's keep the other PR merged and we close this one. @pcarruscag I will deal with the conflicts in your branch now. It's also a good opportunity for me to look at the changes ;)

**Comment by oleburghardt** [comment]
Thanks at all for being so responsive to this mishap.

When I started contributing I learned that something like a 2-LGTM-rule was applying. But apparently it evolved to have someone merge a pull request if he or she can judge the content and feels comfortable with it, as the other approach ended up having a large list of unmerged pull requests **or** having two LGTM's of non-independent reviewers.

@economon Maybe you can bring it up at the next meeting how we could address this little double bind?

So sorry again for the trouble (at least a revert of the very latest commit would not be too difficult). Still I'll wait if @pcarruscag and @talbring want to do now the way Tim suggested.

**Comment by pcarruscag** [comment]
I'll fix my branch. If you do not have time for reviews I am not going to ask you to fix my code.

**Pull request closed without merging**
