### PR TITLE
fixed error for 64bit platform during pointer conversion

### PR DESCRIPTION
**Pull request by libm3l**
replaced pointer conversion by atoi function, previous implementation caused compilation error on newer 64 bit platform compilers

### CODE REVIEW

**Comment by economon** [comment]
Hi Adam,

Thanks for the fix. This is over in the source for the TecIO library (not our own source, but Tecplot kindly allows us to distribute), so it is less familiar to me. Do you know why this error occurs for you?

I am open to modifying this version within our SU2 distribution, but perhaps we should make the Tecplot folks aware of any issues as well.

Tom

**Comment by libm3l** [comment]
Hi Tom

I do not know why it happened on my laptop and not on any other computer
I compiled SU2.

One thing may be that I'm running on gentoo and have pretty upstream
distribution of C++, but this is just my guess. Do you have a contact to
Tecplot?
If you want, send them a notification otherwise I would do it.

Adam

**Comment by economon** [comment]
Yes, I will connect you on a new thread over email shortly...

**Comment by economon** [comment]
Hi Adam,

Any updates on a resolution for this? I know there was some ongoing discussion with Tecplot on the issue. We may need to resubmit the modification in a new PR to sync up the branches, since a lot has changed lately...

Tom

**Comment by libm3l** [comment]
Hi Tom

No news from Tecplot. I tried a couple of things and it did not work.
They then took over and I have not heard from them since then.

Adam

**Comment by economon** [comment]
Adam: I noticed you updated this PR with some changes. Are you happy with this change to the TecIO library now?

Also, it looks like you updated some of the configure to v1.15. Was this required for your changes? We typically use v1.12, which we ship with the source code in externals/autotools. This will be built for you automatically and autoreconf will be called if you use the SU2/bootstrap script.

**Comment by davetaflin** [comment]
Here are the proposed changes:

-                Result->Value = (ArbParam_t)strCopy;
+                Result->Value = atoi(strCopy);

-                              AuxName, (ArbParam_t)AuxValue,
+                              AuxName, atoi(AuxValue),

The existing lines cast a string pointer to an integer (ArbParam_t is an integer type). Lower-level code will re-cast this back to a string pointer and dereference it. The proposed replacement lines read an integer from the string. Attempting to cast the resulting value to a pointer and dereference it will cause a crash.

To make newer compilers happy, I’d suggest replacing the c-style cast with a reinterpret cast:

-                Result->Value = (ArbParam_t)strCopy;
+                Result->Value = reinterpret_cast<ArbParam_t>(strCopy);

-                              AuxName, (ArbParam_t)AuxValue,
+                              AuxName, reinterpret_cast<ArbParam_t> (AuxValue),

**Comment by economon** [comment]
@libm3l: if you have the time, could you please apply the suggested changes above from Tecplot (thanks, @davetaflin!)? It is probably best to start with a fresh branch without the changes to the autotools stuff that show up in the commits on this PR in order to avoid some conflicts when we merge. Thanks!

**Comment by economon** [comment]
@libm3l : as this PR has become out of date, I have added this fix to #598 that was just submitted so we can close this one. Thanks again for your contribution!

**Pull request closed without merging**
