### PR TITLE
Feature outflow adjoint

### PR DESCRIPTION
**Pull request by hlkline**
If 'downstream_function.py' is put in the run directory, whatever function is defined there will be used by finite_differences.py and continuous_adjoint.py with newly implemented boundary conditions that allow passing in gradients from an external function (or defined manually as constants in the config file). 
These are accessed with the "OUTLET_CHAIN_RULE" objective and can also be used with optimization.

Other changes:
- addition of downstream_function.py in SU2_PY folder: if used this should be copied to the run directory and modified to contain whatever function of interest you want. Limited to quasi 1D functions for now.
- back pressure sensitivity output to screen and convergence history if an outflow-based objective is specified (average pressure, outlet-chain-rule, etc)
- 2D symmetry plan now allows movement in the direction of the symmetry line (previously deformations intersecting a symmetry plane resulted in undesired deformations)

### CODE REVIEW

**Comment by economon** [comment]
@hlkline, looks like there are conflicts in the pull request... When you have a moment, could you please check it out so that we can get this merged in soon?

**Comment by hlkline** [comment]
hmm there weren't when I submitted it but I'll see what's up, I'm assume
some more recent commits to develop.

On Tue, Oct 27, 2015 at 1:36 PM, Thomas D. Economon <
notifications@github.com> wrote:

> @hlkline <https://github.com/hlkline>, looks like there are conflicts in
> the pull request... When you have a moment, could you please check it out
> so that we can get this merged in soon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/su2code/SU2/pull/204#issuecomment-151636306>.
>



-- 
Heather Kline
PhD Candidate, NASA Space Technology Research Fellow
Aeronautics & Astronautics
Stanford University
kline.hl@gmail.com, hlkline@stanford.edu

**Comment by hlkline** [comment]
@talbring if you have a minute to take a look at how I've handled these objectives in iteration_structure.cpp that would be much appreciated.
I think I have resolved the conflicts; the source of most of the problems was with registering outflow-based objective functions which depend on values that were only calculated at an output step. This meant adding an if statement to calculate these values at the most recent point where the output container was available.

**Comment by talbring** [comment]
Looks good to me. This is exactly how I would do it.

**Comment by economon** [comment]
Aok. Looks good now. Merging this in...

**Pull request merged**
