### PR TITLE
Feature error message

### PR DESCRIPTION
**Pull request by vdweide**
## Proposed Changes
This small PR modifies the error handling, such that the error message is also written when the call to the error handler is not collective. The function CBaseMPIWrapper::Error is not so small anymore, so it may be an idea to move it to the .cpp file instead of inlining it.
 
## Related Work
N/A

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [ X] I am submitting my contribution to the develop branch.
- [ X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [ X] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.

### CODE REVIEW

**Comment by vdweide** [comment]
I forgot to mention that MPI-3 functionality is required for these changes. Can we assume that all practical MPI implementations support the MPI-3 standard or should we add a test in configure to check?

**Comment by vdweide** [comment]
The MPI version used by travis is too old to support all the new MPI functions. Canceling this one for now.

**Comment by vdweide** [comment]
I ifdeffed the availability of MPI_Ibarrier for checking whether the error call is collective. If MPI_Ibarrier is not present, there is a delay in the writing of the error message of 1 second (to make sure that the buffers for the one-sided communication are updated). If MPI_Ibarrier should be used when available (this is the cleaner solution), an additional check in configure must be added.

**Comment by talbring** [comment]
Thanks @vdweide. This looks like a good solution. I think we could determine whether MPI_IBarrier is available or not from the version macro that the MPI implementations provide.

**Comment by vdweide** [comment]
@talbring, is it easy to add such a test to configure? I have no idea how to do this to be honest?

**Comment by vdweide** [comment]
According to the MPI standard the macro MPI_VERSION should be defined. However, even if it is not defined, the MPI_Ibarrier will not be called. This is exactly what you want. I'll push these changes shortly and see if the regression tests go through.

**Comment by talbring** [comment]
Perfect, that looks good! No further comments, will merge that in soon.

**Comment by vdweide** [comment]
Alright, merging in then.

**Comment by vdweide** [comment]
Looks like I screwed up the merge

**Pull request merged**
