### PR TITLE
Feature pre-accumulation for the structural solver

### PR DESCRIPTION
**Pull request by pcarruscag**
## Proposed Changes
Use of pre-accumulation in the structural solver numerics to provide order of magnitude reduction in the adjoint structural solver memory footprint.

Using the fact that only the RHS of linear systems is differentiated, we can use pre-accumulation on the nodal stress residual computed in CFEAElasticity::Compute_Tangent_Matrix and CFEAElasticity::Compute_NodalStress_Term.
The implementation accounts for material properties and nodal coordinates, the latter are not strictly required at the moment but this future proofs the implementation for structural shape derivatives. 

The above routines where chosen because "everything" happens inside them: computation of element gradients, constitutive terms, stress tensors, etc. So it is where the technique would be most effective.

## Related Work
*Resolve any issues (bug fix or feature request), note any related PRs, or mention interactions with the work of others, if any.*

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [X] I am submitting my contribution to the develop branch.
- [X] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags).
- [X] My contribution is commented and consistent with SU2 style.

### CODE REVIEW

**Comment by pcarruscag** [comment]
Test case discadj_fea is failing due to a change of residuals (the derivatives are the same up to the displayed precision), the change in residuals is smaller than that caused by running on 2 cores rather than serial. Further investigation needed nevertheless.

**Comment by pcarruscag** [comment]
I updated the reference values.
Running the case for more iterations and with tighter tolerances on the linear solver, and comparing preaccumulation on vs off, in serial and parallel, the conclusion is that the derivatives are the same to the 10th decimal place. Which is of the order of the residual reduction, and of the order of the variation between consecutive iterations at convergence.
The data on which I base the conclusion -> [investigation.zip](https://github.com/su2code/SU2/files/2446386/investigation.zip)

**Comment by talbring** [comment]
@pcarruscag To me it looks ok!

**Comment by rsanfer** [comment]
Thanks @pcarruscag! LGTM. I had a go at the results that you shared and as you mentioned the changes in the sensitivities are in the order of the convergence level. Happy to get this merged in.

**Comment by pcarruscag** [comment]
Great! In it goes then.

**Pull request merged**
