### PR TITLE
Update of Codi to the most recent version.

### PR DESCRIPTION
**Pull request by talbring**
I opened this pull request to let the AD regression tests run. Once this is finished, it can directly be merged.

### CODE REVIEW

**Comment by talbring** [comment]
I had to change the compiler version for the AD binaries to gcc-4.7. The normal binaries are still compiled with the default ones in travis.

**Comment by talbring** [comment]
Yes, the minimum required version is now 4.7 (which has full C++11 support). But only for the AD binaries!
We have to move forward, otherwise it is not possible to include current and future changes that improve the performance. But I can provide a patch to make it work with gcc < 4.7 if necessary.

**Comment by economon** [comment]
Understood. Just want to make sure we all know the requirements. We might want to put this in the docs. Could you please add a note on the AD build page of the wiki?

**Comment by talbring** [comment]
Yes, i'll add a comment to wiki then.

**Pull request merged**
