### PR TITLE
Fix cross compilation

### PR DESCRIPTION
**Pull request by MicK7**
## Proposed Changes
Detect when meson can run configuration test or if cross compiling for cgns hdf5 backend
 

## Related Work
*Resolve any issues (bug fix or feature request), note any related PRs, or mention interactions with the work of others, if any.*

## PR Checklist
*Put an X by all that apply. You can fill this out after submitting the PR. If you have any questions, don't hesitate to ask! We want to help. These are a guide for you to know what the reviewers will be looking for in your contribution.*

- [x] I am submitting my contribution to the develop branch.
- [x] My contribution generates no new compiler warnings (try with the '-Wall -Wextra -Wno-unused-parameter -Wno-empty-body' compiler flags, or simply --warnlevel=2 when using meson).
- [ ] My contribution is commented and consistent with SU2 style.
- [ ] I have added a test case that demonstrates my contribution, if necessary.
- [ ] I have updated appropriate documentation (Tutorials, Docs Page, config_template.cpp) , if necessary.

### CODE REVIEW

**Comment by MicK7** [comment]
@pcarruscag This PR should fix the production issue.

**Review by pcarruscag — APPROVED** [review]

**Comment by pcarruscag** [comment]
Thanks @MicK7 do think updating meson would help with the macos issue?

**Comment by MicK7** [comment]
@pcarruscag Yes as it is a different issue.

**Comment by pcarruscag** [comment]
:+1: Ok @MicK7 PR already open.
Different cross compile issue now https://github.com/su2code/SU2/runs/4900536101?check_suite_focus=true
```
ERROR: 
Cannot use target H5detect as a generator because it is built for the
host machine and no exe wrapper is defined or needs_exe_wrapper is
true. You might want to set `native: true` instead to build it for
the build machine.
```

**Pull request merged**
