### PR TITLE
Feature Python Wrapper - Test cases

### PR DESCRIPTION
**Pull request by tobadavid**
This pull request introduces new test cases for the Python wrapper. The first set of tests includes:

- Classical CFD test cases: euler naca0012, rans naca0012, unsteady square cylinder, aeroelastic
- A native FSI test case involving the FSIDriver of SU2: wall channel 2D

These tests are launched using the script pyWrap_SU2_CFD.py being the Py wrapped version of the executable SU2_CFD. 

The second set of tests includes:

- A new FSI test case involving the coupling between SU2 and an external structural solver (see TestCases/coupled_fsi/2d_aeroelasticity). 

The structural solver is the PitchPlungeAirfoilStructuralTester (see SU2_PY/FSI directory). It was directly written in Python and designed only for this particular test where we measure the aeroelastic response of a pitch-plunge NACA 0012 airfoil under the flutter point. The structural solver tester also illustrates the architecture that is expected for the solid side of the coupling (how the solver is driven, how does the communication layer look like). This test is launched using the script fsi_computation.py (**note** : a parallel run requires mpi4py to be installed on the system). 

The serial_ and parallel_regression.py files were simply modified in order to add those sets of test cases. The first set uses a direct comparaison based on residuals, lift, drag,... whereas the second set uses a comparaison based on output files coming from the structural solver.

In order to build the Py wrapper and run the tests on travis, the preconfigure.py script was adapted so that the option --enable-PY_WRAPPER can be used. Because Swig and mpi4py are required for the build and for the parallel run respectively, they were also introduced in the travis configuration file where mpi4py can be simply installed using the python-pip package.

### CODE REVIEW

**Comment by economon** [comment]
Thanks for putting the tests together, David. We'll get this merged asap to ensure that future commits do not break the wrapper.

@talbring, when you have a moment, can you please verify that the small changes to preconfigure.py won't hurt anything?

**Comment by talbring** [comment]
This change looks ok to me, but in general preconfigure.py should be able to just pass unknown arguments to the configure script so that no change is required there. Have you tried that ?

**Comment by tobadavid** [comment]
I have just made a quick test. Because --enable-PY_WRAPPER is not in the form of --key=value (like --prefix=PREFIX or --with-cc=mpicc), it is not automatically included in the argument_dict dictionary and thus not passed to the configure script. That is why a treated this option in the same way as the --enable-mpi option, just to be sure.

Any advice on how should I treat this --enable-PY_WRAPPER option without changing the ./preconfigure.py ? Or do we just keep everything like it is ?

**Comment by economon** [comment]
Ok.. thanks for the feedback. We'll go ahead with the current version (handled like the --enable-mpi option) for now.

**Comment by talbring** [comment]
Ah you are right, I have actually never thought about that. Then you can ignore my comment ... Looks good !

**Pull request merged**
