### PR TITLE
Updated Adjoint variable to Continuous_Adjoint

### PR DESCRIPTION
**Pull request by fpalacios**
Variable name change (Adjoint -> ContinuousAdjoint). There is now a clear distinction between DiscreteAdjoint variable and ContinuousAdjoint variable (booleans).

I have also fixed some bugs in the I/O (tecplot and fieldview) due to the previous problem: we were using only the Adjoint boolean and the Discrete adjoint output was incorrect.

An interesting bug in geometry.py has been also fixed. We must keep an eye on shape design using geometrical constraints. Because of this problem, it is not working in the master repository and current release.

### CODE REVIEW

**Comment by economon** [comment]
Thanks for the fixes, Francisco. The continuous adjoint tests are now failing, but I am guessing that it is something simple with the changes to the config option. Can you please take a look when you have a moment?

Couldn't agree more about keeping an eye on the Python scripts. We'll chat about it this week at the developer meeting (we need regressions for the Python scripts). More on that to come.

**Comment by fpalacios** [comment]
Thanks, I’ll take a look at that before the weekend,


Best,
Francisco

**Comment by economon** [comment]
This was more critical than I originally thought (I just ran into another issue related to it). The fix was a very small one.. I think the tests will pass now. We'll merge this in right away after that.

**Comment by fpalacios** [comment]
Thanks for the fix!

Francisco

**Pull request merged**
