### PR TITLE
Add Python 3.7 to Travis config

### PR DESCRIPTION
**Pull request by petebachant**
Adding Python 3.7 to test environments in light of #620.

### CODE REVIEW

**Comment by petebachant** [comment]
Hmmm this didn't work because Travis doesn't have a Python 3.7 binary to download, even though it wouldn't be used. Going to require some more thought if this is worth testing for.

**Comment by talbring** [comment]
We should also think of a smarter way of setting up the travis system. Running 12 independent jobs, each of them having to compile the whole code multiple times, just to test python is a little bit of an overhead.

**Comment by petebachant** [comment]
Not sure if it's preferable, but I changed the environment to use the latest available Python 3, rather than 3.6, and the tests still pass with Python 3.7.

**Comment by economon** [comment]
@petebachant : do you have any ideas about the failure in #620 posted by @galbramc ?

**Comment by petebachant** [comment]
The use of SU2deform in #620 is apparently not part of the test suite, so testing with Python 3.7 doesn't replicate the issue.

**Comment by petebachant** [comment]
Yep, I don't know of any changes to `map` from Python 3.6 to Python 3.7.

**Pull request closed without merging**
