### PR TITLE
Code cleaning

### PR DESCRIPTION
**Pull request by fpalacios**
Hi,

As in previous years, I have performed an extensive cleaning of SU2 for the sake of code clearness, memory optimization and speed. Remember that nothing has been permanently removed from the git server and I encourage the developers to recover some of the removed code as a branch and continue working on it. Obviously, I have been very careful to do not remove any active implementation.

I have also fixed some bugs and issues with the C++ compilation under Windows. Now, it should be a straightforward process.

Thanks,
Francisco

### CODE REVIEW

**Comment by btracey** [comment]
Could you leave in the machine learning section a bit longer?

**Comment by fpalacios** [comment]
No… I can’t.  I’m sorry.

Great to hear from you. Machine learning is a very valuable research work and I will add it as a feature branch. 

Removing code from the main release is a complex task and, as in the past, I have taken tough decisions. Anyway, to maintain a clean code is critical for its growing, it is like trimming a large tree.

Basic criteria to maintain forever an implementation on the develop->master branch are: - Clear benefit to the CFD community (more accurate, robust, etc.) - Existing community of users or active developers - Minimal code documentation (at least the options should be in the config file). - Easy to install and use. - The implementation style should be aligned with the SU2 style - Regressions tests.


Best,
Francisco

**Comment by economon** [comment]
Francisco, when you have a moment, can you please check out the issue with Travis for this pull request? I think it is related to the autotools during the build...

**Comment by btracey** [comment]
Ok. Thanks for the reply. If it's not simple to separate into a branch, don't worry. I have already downloaded the current master and can maintain a local copy.

I see that there is at least one issue related to that segment (I would have responded had I seen it). Are users interested in using that segment of the code? If so, I'd be more than happy to add documentation and a usage example I the develop branch. When thus code went live we decided it was better to not add documentation since the feature is experimental. This is certainly a fixable situation on the develop branch.

**Comment by fpalacios** [comment]
Hi,

Mmm… it is strange, it is working for me:
I have pulled from the develop branch to update feature_cleaning
$./bootstrap to be sure that the makefile.in files have been updated.
$./preconfigure.py --enable-autodiff --with-ad=CODI --enable-mpi -p'--with-cc=mpicc --with-cxx=mpicxx CXXFLAGS="-O3”'
$make install
And everything seems ok.


Tom, if you have a while, could you please checkout feature_cleaning and try to compile? Maybe my configuration is different from travis.

Thanks,
Francisco

**Comment by economon** [comment]
Closer. It was just a versioning problem with the autotools.

Looks like all we need to do now is clean up some old options left in the test case config files causing them to fail.

**Comment by economon** [comment]
Thank you for taking the time to clean things up, Francisco. This is no easy task, and it is critically important for the health of the code.

Everything looks good to me. Merging this in now.

**Pull request merged**
