### PR TITLE
Automatic Doxygen Documentation

### PR DESCRIPTION
**Pull request by talbring**
This is a pull request to test the generation of the doxygen documentation. It is currently set up to upload the documentation (i.e. to push to the Doxygen repository) if there is a push to the master or develop branch. For any other branch or pull request it will still run the generation so that we can look for warnings etc. 

The documentation will be visible here:

- develop: https://su2code.github.io/Doxygen/develop/html/index.html
- master:  https://su2code.github.io/Doxygen/master/html/index.html

Eventually we will add these links (or at least the one to the master) to the website.

It uses the new stages feature of travis. In the future we might also add a deployment stage for automating the release process.

### CODE REVIEW

**Comment by hlkline** [comment]
I'm glad to see the doxygen being used again, thanks for setting this up! Was this something needing review, or is it just a test that won't be merged?

**Comment by talbring** [comment]
It works already better than I expected. I am gonna play around with it a little bit longer, but I think we can use the PR soon to merge it in soon.

**Comment by vdweide** [comment]
@talbring, in March you mentioned that it was almost ready to be merged in. Is that still the case?

**Comment by talbring** [comment]
Hm although the whole process works nicely, the repo size grows too fast ... I am thinking of some alternatives at the moment.

**Pull request closed without merging**
