### PR TITLE
Feature deformation

### PR DESCRIPTION
**Pull request by hlkline**
recently (in develop) scale/rotate/translate were changed to do volume deformations (aka, all at once and not requiring a linear elasticity solve to get the updated volume mesh). This branch includes changes to allow scaling, translating, or rotating only a surface w/in the volume. If all markers are included in the deformation, it returns to the all-at-once volume deformation. 

Hypothetically this should allow multi-body movements (as in, rotating a control surface) while maintaining the more efficient volume deformation for operations like scaling the mesh.

### CODE REVIEW

**Comment by hlkline** [comment]
Some illustrative images/output in case my description was hard to understand:
image

SU2_DEF output when only "airfoil" marker included:
```c++
------------------------- Surface grid deformation ----------------------
Performing the deformation of the surface grid.

----------------------- Volumetric grid deformation ---------------------
Performing the deformation of the volumetric grid.

# FGMRES residual history
# Residual tolerance target = 4.14044e-11
# Initial residual norm     = 15.8102
     0     1
     50     2.17385e-06
     100     1.08998e-10
# FGMRES final (true) residual:
# Iteration = 105: |res|/|res0| = 3.50764e-11.

Non-linear iter.: 1/1. Linear iter.: 105. Min. area: 4.1019e-08. Error: 5.54565e-10.

----------------------- Write deformed grid files -----------------------
Merging grid connectivity.
Merging grid coordinates.
Writing volume mesh file.
Writing surface mesh file.
Writing .su2 file.
Adding any FFD information to the SU2 file.

Completed in 1.039217 seconds on 1 core.

------------------------- Exit Success (SU2_DEF) ------------------------
```

image
SU2_DEF: output when deforming with all markers included:
```c++
------------------------- Surface grid deformation ----------------------
Performing the deformation of the surface grid.
No surface deformation (scaling, rotation, or translation).

----------------------- Volumetric grid deformation ---------------------
Performing a translation of the volumetric grid.
Translational displacement: (1, 0, 0).

----------------------- Write deformed grid files -----------------------
Merging grid connectivity.
Merging grid coordinates.
Writing volume mesh file.
Writing surface mesh file.
Writing .su2 file.
Adding any FFD information to the SU2 file.

Completed in 0.716938 seconds on 1 core.
```
as far as I can tell the regression test failure is the same as for the current develop branch; I'll update this pull request whenever that is resolved.

**Comment by economon** [comment]
Thanks for adding the description, Heather. I think this is a very nice contribution.. we’re working on the regressions and will pull this in once we have everything straightened out (and this branch passes).

In the meantime, you got me thinking: the scale, rotate, translate options might be confusing now if a user doesn’t know whether to include the markers or not. Perhaps this is a chance for separating some of the “design” options from “mesh” options.

One way I could see us do this is by moving the implementation I had just committed for the “volume” scale, rotate, and translate options over into the SU2_MSH executable, which might be a more logical home for it. However, this would require adding an extra set of config options for reading in a scale/rotate/translate options for SU2_MSH. The nice thing here is that we keep the intent separate, i.e., only design variables are listed with the other design variables while the mesh transformations are elsewhere.

A different, possibly simpler way would be to just create separate names for these two types in the list of available options so that there is no ambiguity.

Any thoughts?


On Aug 16, 2015, at 9:21 AM, Heather Kline <notifications@github.com<mailto:notifications@github.com>> wrote:


Some illustrative images/output in case my description was hard to understand:
[image]<https://cloud.githubusercontent.com/assets/5167760/9294050/52a764b2-440f-11e5-8681-b68318da0ce7.png>

SU2_DEF output when only "airfoil" marker included:

------------------------- Surface grid deformation ----------------------
Performing the deformation of the surface grid.

----------------------- Volumetric grid deformation ---------------------
Performing the deformation of the volumetric grid.

# FGMRES residual history
# Residual tolerance target = 4.14044e-11
# Initial residual norm     = 15.8102
     0     1
     50     2.17385e-06
     100     1.08998e-10
# FGMRES final (true) residual:
# Iteration = 105: |res|/|res0| = 3.50764e-11.

Non-linear iter.: 1/1. Linear iter.: 105. Min. area: 4.1019e-08. Error: 5.54565e-10.

----------------------- Write deformed grid files -----------------------
Merging grid connectivity.
Merging grid coordinates.
Writing volume mesh file.
Writing surface mesh file.
Writing .su2 file.
Adding any FFD information to the SU2 file.

Completed in 1.039217 seconds on 1 core.

------------------------- Exit Success (SU2_DEF) ------------------------

[image]<https://cloud.githubusercontent.com/assets/5167760/9294056/7be9439a-440f-11e5-862f-742246ef1565.png>
SU2_DEF: output when deforming with all markers included:

------------------------- Surface grid deformation ----------------------
Performing the deformation of the surface grid.
No surface deformation (scaling, rotation, or translation).

----------------------- Volumetric grid deformation ---------------------
Performing a translation of the volumetric grid.
Translational displacement: (1, 0, 0).

----------------------- Write deformed grid files -----------------------
Merging grid connectivity.
Merging grid coordinates.
Writing volume mesh file.
Writing surface mesh file.
Writing .su2 file.
Adding any FFD information to the SU2 file.

Completed in 0.716938 seconds on 1 core.

as far as I can tell the regression test failure is the same as for the current develop branch; I'll update this pull request whenever that is resolved.

**Comment by hlkline** [comment]
Thanks Tom
I agree that we should make things easy to understand. 
My thinking was that most users will want to know what parts of the mesh they are moving, but don't necessarily need to know what's happening underneath - if they specify the entire mesh the code just reverts to the more efficient method. But (from the users perspective) it may be just as easy to have a separate specification for scaling the entire mesh. 

In terms of moving it to SU2_MSH; I think it may make sense to include scale/rotate/translate in SU2_MSH, but I think it would be confusing to have two options that do the same thing. I would side with separate option names (this would also eliminate a loop over markers in this pull request)

On this topic, I have sometimes found MARKER_DESIGNING and DV_MARKER to be confusing; on their own they sound very similar, in the description MARKER_DESIGNING is where the objective function is evaluated - but in the code, it's not clear what MARKER_DESIGNING does - the surfaces specified by MARKER_MONITORING are what are actually used to evaluate the objective function value. 

There may be other similar areas where config file options could be clarified or compressed.

**Comment by fpalacios** [comment]
Thanks Heather,

I completely agree, MARKER_DESIGNING. MARKER_MONITORING. MARKER_PLOTTING. DV_MARKER are confusing… we have tried to fix this without too much luck. It really requires some deep changes on the python and C++ stuff. The idea is the following.

> MARKER_PLOTTING: Should disappear, in the future, all the markers should be in the tecplot or paraview file (and the user will decide which one turn on of off using templet of paraview)


> MARKER_MONITORING, MARKER_DESIGNING: The main idea is to be able to compute to different integrals over the surfaces: one for simulation and the other for design. e.g. You maybe want to include all the solid surfaces and fan faces, and charging stations in MARKER_MONITORING to compute (Drag-Thrust) but in MArKER DESIGN you are only interested on the wing surface for design.
> 
> DV_MARKER. This is an unfortunately name.  At the very beginning the mesh deformation capability was developed only for shape design (DV = Design Variables). We should generalize the names of the grid deformation parameters without using DV.

Thanks!
Francisco

**Comment by hlkline** [comment]
I really like the idea of being able to plot by the boundary markers - maybe we can write out the tecplot (or paraview) zones by the name given in the mesh file rather than "ZONE_1" always. 

Are you saying that MARKER_MONITORING controls what surface are used to calculate the history file output while MARKER_DESIGNING identifies the surfaces to use for calculating an objective function? In that case, I would suggest adding an output to the history file for the objective (aka, the history file would include "Cd, Cl, .... , <objective> "- this would be a bit repetitive for standard cases where you're just minimizing drag over the entire surface, but could make it easier to start doing more complicated objectives. 
As you say, this involves some deep changes in the python code; we should definitely think about it carefully.

**Comment by economon** [comment]
We're running this through Travis once more right more, but it looks good to me. We'll pull it in if it passes.

It will be good to have these options for design within SU2_DEF. I think as a next step, we will move the rigid scale/rotate/translate options for the full volume mesh to SU2_MSH, which makes more sense philosophically. 

I agree on putting all surfaces into the visualization files (i.e., removing MARKER_PLOTTING). This is on the To Do list. In terms of the others, what if we consider having a MARKER_DESIGNING (same as current) and a new MARKER_DYNAMIC in the place of MARKER_MOVING, which is meant for dynamically moving markers in unsteady problems?

**Comment by hlkline** [comment]
Sounds good. 
Do you mean that MARKER_MOVING will disappear entirely? I think that is a good idea - this is one of those options that confuse new users if they aren't reading the config file comments in detail.

**Comment by economon** [comment]
Merged! Yes, replacing MARKER_MOVING is what I had in mind. We'll work on that in new branch (and subsequent pull request), :).

**Pull request merged**
